import RB31EndToEnd.Combinatorics.ProvenanceFlag
import RB31EndToEnd.Linear.DirectionStress
import RB31EndToEnd.Algebra.FiniteCoordinateTrdeg

/-!
# Function-field branches for provenance flags

An irreducible configuration branch is represented by its actual function
field `K` over a base field `k`, together with the labelled coordinate
functions which generate `K`.  The live coordinate index is literally
`V × Fin 3`: the type `V` contains exactly the live vertices.  Likewise,
every inhabitant of `Flag` is an active provenance flag.

Thus branch dimension is mathlib's native `Algebra.trdeg k K`; it is not an opaque
user-supplied number.  Collinearity and pairwise distinctness are literal
conditions on the coordinate functions.  The structure stores no
codimension, semismallness inequality, or height conclusion.
-/

namespace RB31E2E

noncomputable section

namespace ProvenanceFlag

variable {k K V Flag : Type*}
  [Field k] [Field K] [Algebra k K]
  [Fintype V] [DecidableEq V] [Fintype Flag] [DecidableEq Flag]

/-- The exact finite index type of all live spatial coordinate functions. -/
abbrev LiveCoordinate (V : Type*) := V × Fin 3

/-- The coordinate family of a placement on all (and only) live vertices. -/
def liveCoordinateFamily (a : V → Fin 3 → K) : LiveCoordinate V → K :=
  fun x ↦ a x.1 x.2

/-- The function field is generated by the labelled live coordinates. -/
def GeneratedByLiveCoordinates (a : V → Fin 3 → K) : Prop :=
  IntermediateField.adjoin k (Set.range (liveCoordinateFamily a)) = ⊤

/-- Literal pairwise distinctness on the exact live vertex type. -/
def PairwiseDistinctOnLive (a : V → Fin 3 → K) : Prop :=
  Function.Injective a

/-- All labelled points in `X` lie on one affine line.  The direction is
not required to be nonzero; pairwise distinctness supplies nondegeneracy on
the three-terminal flags where it is needed. -/
def AffinelyCollinearOn (a : V → Fin 3 → K) (X : Finset V) : Prop :=
  ∃ origin direction : Fin 3 → K,
    ∀ v ∈ X, ∃ t : K, a v = origin + t • direction

/-- Every active provenance triple is collinear. -/
def FlagCollinearities (S : State V Flag) (a : V → Fin 3 → K) : Prop :=
  ∀ t : Flag, AffinelyCollinearOn a (S.terminals t)

/--
Honest function-field data for one irreducible flagged configuration branch.
No codimension, stress bound, semismallness statement, or generic-correctness
theorem is a field.
-/
structure FunctionFieldBranch (S : State V Flag) where
  position : V → Fin 3 → K
  generated : GeneratedByLiveCoordinates (k := k) position
  distinct : PairwiseDistinctOnLive position
  collinear : FlagCollinearities S position

/-- The direction-stress dimension at the generic point of the branch. -/
def FunctionFieldBranch.stressDim
    (S : State V Flag) (Y : FunctionFieldBranch (k := k) (K := K) S) : ℕ :=
  DirectionStress.directionStressDim S.edges Y.position

/--
The flag-semismall numerical statement in subtraction-free form:

`stress dimension + branch dimension + 2 * number of active flags`
is at most the full `3 * number of live vertices` ambient dimension.

All dimensions in this definition are read from actual Lean objects:
`ker`, `trdeg`, and the cardinalities of the exact active types.
-/
def FunctionFieldBranch.SemismallBudget
    (S : State V Flag) (Y : FunctionFieldBranch (k := k) (K := K) S) : Prop :=
  (Y.stressDim S : Cardinal) + Algebra.trdeg k K +
      2 * (Fintype.card Flag : Cardinal) ≤
    3 * (Fintype.card V : Cardinal)

/-- The coordinate-generation hypothesis alone gives the ambient branch
dimension bound. -/
theorem FunctionFieldBranch.trdeg_le_ambient
    (S : State V Flag) (Y : FunctionFieldBranch (k := k) (K := K) S) :
    Algebra.trdeg k K ≤ 3 * (Fintype.card V : Cardinal) := by
  exact FiniteCoordinateTrdeg.trdeg_le_three_mul_card
    (liveCoordinateFamily Y.position) Y.generated

/-- Empty-flag specialization of the same transparent budget. -/
theorem FunctionFieldBranch.semismallBudget_of_flag_card_zero_iff
    (S : State V Flag) (Y : FunctionFieldBranch (k := k) (K := K) S)
    (hflags : Fintype.card Flag = 0) :
    Y.SemismallBudget S ↔
      (Y.stressDim S : Cardinal) + Algebra.trdeg k K ≤
        3 * (Fintype.card V : Cardinal) := by
  simp [FunctionFieldBranch.SemismallBudget, hflags]

end ProvenanceFlag

end

end RB31E2E
