import RB31EndToEnd.NullCellule.ProvenanceFlagDeletionLedger
import RB31EndToEnd.Combinatorics.ProvenanceFlagSelection

/-!
# Strong induction for provenance-flag semismallness

This file proves the common strong-induction step: descent of collinearity to
the intrinsic child coordinate field, construction of coordinate-generated
child branches, the empty-live-vertex base case, low-degree selection, and
the two nonexceptional recursive branches.
-/

namespace RB31E2E

noncomputable section

namespace ProvenanceFlag

open DirectionStress

universe u v w x

variable {k : Type u} {K : Type v} {V : Type w} {Flag : Type x}
  [Field k] [Field K] [Algebra k K]
  [Fintype V] [DecidableEq V] [Fintype Flag] [DecidableEq Flag]

/-! ## Collinearity descends to a coordinate field -/

omit [Fintype V] [DecidableEq V] [Fintype Flag] [DecidableEq Flag] in
/-- Three points valued in an intermediate field are already collinear over
that field if their scalar extensions are collinear and the first two are
distinct.  The scalar is the ratio of two retained coordinates, so no
closure or algebraic-geometry descent theorem is assumed. -/
theorem collinear_restrictScalars
    (L : IntermediateField k K)
    (p q r : Fin 3 → L) (hpq : p ≠ q)
    (hcol : PinCollinearity.Collinear
      (fun j ↦ (p j : K)) (fun j ↦ (q j : K)) (fun j ↦ (r j : K))) :
    PinCollinearity.Collinear p q r := by
  have hpqK : (fun j ↦ (p j : K)) ≠ (fun j ↦ (q j : K)) := by
    intro h
    apply hpq
    funext j
    exact Subtype.ext (congrFun h j)
  obtain ⟨s, hs⟩ :=
    (collinear_iff_exists_smul_difference
      (fun j ↦ (p j : K)) (fun j ↦ (q j : K))
      (fun j ↦ (r j : K)) hpqK).1 hcol
  have hCoordinate : ∃ j : Fin 3, q j - p j ≠ 0 := by
    by_contra h
    push Not at h
    apply hpq
    funext j
    exact sub_eq_zero.mp (h j) |>.symm
  obtain ⟨j, hj⟩ := hCoordinate
  let t : L := (r j - p j) / (q j - p j)
  have hsEq : s = (t : K) := by
    have hsj := congrFun hs j
    change (r j : K) - p j = s * ((q j : K) - p j) at hsj
    have hjK : (q j : K) - p j ≠ 0 := by
      intro hzero
      apply hj
      apply Subtype.ext
      exact hzero
    apply (eq_div_iff hjK).2
    exact hsj.symm
  apply (collinear_iff_exists_smul_difference p q r hpq).2
  refine ⟨t, ?_⟩
  funext i
  apply Subtype.ext
  have hi := congrFun hs i
  change (r i : K) - p i = s * ((q i : K) - p i) at hi
  change (r i : K) - p i = (t : K) * ((q i : K) - p i)
  rw [← hsEq]
  exact hi

omit [Fintype V] [Fintype Flag] [DecidableEq Flag] in
/-- A three-element collinear terminal set remains affinely collinear after
restricting all its coordinates to an intermediate field. -/
theorem affinelyCollinearOn_intrinsic
    (L : IntermediateField k K)
    (a : V → Fin 3 → L) (X : Finset V)
    (hCard : X.card = 3)
    (hDistinct : Function.Injective a)
    (hAmbient : AffinelyCollinearOn
      (fun v j ↦ ((a v j : L) : K)) X) :
    AffinelyCollinearOn a X := by
  obtain ⟨p, q, r, hpq, hpr, hqr, hX⟩ := Finset.card_eq_three.mp hCard
  have hp : p ∈ X := by rw [hX]; simp
  have hq : q ∈ X := by rw [hX]; simp
  have hr : r ∈ X := by rw [hX]; simp
  have hpqA : a p ≠ a q := fun h ↦ hpq (hDistinct h)
  have hcolK := pinCollinear_of_affinelyCollinearOn
    (fun v j ↦ ((a v j : L) : K)) X p q r hAmbient hp hq hr
  have hcolL : PinCollinearity.Collinear (a p) (a q) (a r) :=
    collinear_restrictScalars L (a p) (a q) (a r) hpqA hcolK
  obtain ⟨t, ht⟩ :=
    (collinear_iff_exists_smul_difference (a p) (a q) (a r) hpqA).1 hcolL
  refine ⟨a p, a q - a p, ?_⟩
  intro z hz
  rw [hX] at hz
  simp only [Finset.mem_insert, Finset.mem_singleton] at hz
  rcases hz with rfl | rfl | rfl
  · exact ⟨0, by simp⟩
  · exact ⟨1, by module⟩
  · refine ⟨t, ?_⟩
    funext i
    have hi := congrFun ht i
    simp only [Pi.sub_apply, Pi.add_apply, Pi.smul_apply, smul_eq_mul] at hi ⊢
    linear_combination hi

/-! ## Genuine intrinsic child function-field branches -/

/-- The outside-deletion child over the field generated by its own
retained coordinates. -/
def FunctionFieldBranch.deleteOutsideIntrinsic
    (S : State V Flag) (Y : FunctionFieldBranch (k := k) (K := K) S)
    (v : V) (hv : S.flagMultiplicity v = 0) :
    FunctionFieldBranch
      (k := k) (K := retainedLiveCoordinateField (k := k) Y.position v)
      (S.deleteOutside v hv) where
  position := intrinsicRestrictedPlacement (k := k) Y.position v
  generated := intrinsicRestrictedPlacement_generated (k := k) Y.position v
  distinct := by
    intro a b hab
    apply Subtype.ext
    apply Y.distinct
    funext j
    exact congrArg Subtype.val (congrFun hab j)
  collinear t := by
    let L := retainedLiveCoordinateField (k := k) Y.position v
    let childPosition := intrinsicRestrictedPlacement (k := k) Y.position v
    apply affinelyCollinearOn_intrinsic
      (k := k) (K := K) L childPosition
      ((S.deleteOutside v hv).terminals t)
      ((S.deleteOutside v hv).terminals_card t)
    · intro a b hab
      apply Subtype.ext
      apply Y.distinct
      funext j
      exact congrArg Subtype.val (congrFun hab j)
    · exact (Y.toPlacement S).deleteOutsidePlacement S v hv |>.collinear t

/-- The private-deletion child over its own intrinsic coordinate field. -/
def FunctionFieldBranch.deletePrivateIntrinsic
    (S : State V Flag) (Y : FunctionFieldBranch (k := k) (K := K) S)
    (v : V) (t : Flag)
    (hOne : S.flagMultiplicity v = 1) (hvt : v ∈ S.terminals t) :
    FunctionFieldBranch
      (k := k) (K := retainedLiveCoordinateField (k := k) Y.position v)
      (S.deletePrivate v t hOne hvt) where
  position := intrinsicRestrictedPlacement (k := k) Y.position v
  generated := intrinsicRestrictedPlacement_generated (k := k) Y.position v
  distinct := by
    intro a b hab
    apply Subtype.ext
    apply Y.distinct
    funext j
    exact congrArg Subtype.val (congrFun hab j)
  collinear r := by
    let L := retainedLiveCoordinateField (k := k) Y.position v
    let childPosition := intrinsicRestrictedPlacement (k := k) Y.position v
    apply affinelyCollinearOn_intrinsic
      (k := k) (K := K) L childPosition
      ((S.deletePrivate v t hOne hvt).terminals r)
      ((S.deletePrivate v t hOne hvt).terminals_card r)
    · intro a b hab
      apply Subtype.ext
      apply Y.distinct
      funext j
      exact congrArg Subtype.val (congrFun hab j)
    · exact (Y.toPlacement S).deletePrivatePlacement
        S v t hOne hvt |>.collinear r

/-! ## Intrinsic recursive budgets feed the deletion ledger -/

/-- A recursive budget for the genuine intrinsic outside child is exactly
the intrinsic form of the ambient child placement budget expected by the
outside deletion ledger. -/
theorem FunctionFieldBranch.deleteOutsidePlacement_semismallBudget_of_intrinsic
    (S : State V Flag) (Y : FunctionFieldBranch (k := k) (K := K) S)
    (v : V) (hv : S.flagMultiplicity v = 0)
    (hChild :
      (Y.deleteOutsideIntrinsic S v hv).SemismallBudget
        (S.deleteOutside v hv)) :
    PlacementBranch.SemismallBudget (k := k)
      (S.deleteOutside v hv)
      ((Y.toPlacement S).deleteOutsidePlacement S v hv) := by
  apply (PlacementBranch.deleteOutside_semismallBudget_iff_intrinsic
    (k := k) S (Y.toPlacement S) v hv).2
  simpa only [FunctionFieldBranch.SemismallBudget,
    FunctionFieldBranch.stressDim] using hChild

/-- The corresponding bridge for a private child, whose intrinsic flag
type has already forgotten the consumed flag. -/
theorem FunctionFieldBranch.deletePrivatePlacement_semismallBudget_of_intrinsic
    (S : State V Flag) (Y : FunctionFieldBranch (k := k) (K := K) S)
    (v : V) (t : Flag)
    (hOne : S.flagMultiplicity v = 1) (hvt : v ∈ S.terminals t)
    (hChild :
      (Y.deletePrivateIntrinsic S v t hOne hvt).SemismallBudget
        (S.deletePrivate v t hOne hvt)) :
    PlacementBranch.SemismallBudget (k := k)
      (S.deletePrivate v t hOne hvt)
      ((Y.toPlacement S).deletePrivatePlacement S v t hOne hvt) := by
  apply (PlacementBranch.deletePrivate_semismallBudget_iff_intrinsic
    (k := k) S (Y.toPlacement S) v t hOne hvt).2
  simpa only [FunctionFieldBranch.SemismallBudget,
    FunctionFieldBranch.stressDim] using hChild

/-- **Outside nonexceptional induction step.**  This is the complete
recursive branch: intrinsic child semismallness plus the transparent local
nonexceptional condition implies the parent budget. -/
theorem FunctionFieldBranch.semismallBudget_of_deleteOutsideIntrinsic
    (S : State V Flag) (Y : FunctionFieldBranch (k := k) (K := K) S)
    (v : V) (hv : S.flagMultiplicity v = 0)
    (hChild :
      (Y.deleteOutsideIntrinsic S v hv).SemismallBudget
        (S.deleteOutside v hv))
    (hNonexceptional :
      OutsideNonexceptional (k := k) S.edges Y.position v) :
    Y.SemismallBudget S := by
  apply Y.semismallBudget_of_deleteOutside S v hv
    (Y.deleteOutsidePlacement_semismallBudget_of_intrinsic
      S v hv hChild)
  exact outside_local_payment S.edges Y.position v Y.generated hNonexceptional

/-- **Private nonexceptional induction step.**  The removed flag pays two
of the three deleted vertex coordinates, leaving precisely the local
allowance certified by `PrivateNonexceptional`. -/
theorem FunctionFieldBranch.semismallBudget_of_deletePrivateIntrinsic
    (S : State V Flag) (Y : FunctionFieldBranch (k := k) (K := K) S)
    (v : V) (t : Flag)
    (hOne : S.flagMultiplicity v = 1) (hvt : v ∈ S.terminals t)
    (hChild :
      (Y.deletePrivateIntrinsic S v t hOne hvt).SemismallBudget
        (S.deletePrivate v t hOne hvt))
    (hNonexceptional :
      PrivateNonexceptional (k := k) S.edges Y.position v) :
    Y.SemismallBudget S := by
  apply Y.semismallBudget_of_deletePrivate S v t hOne hvt
    (Y.deletePrivatePlacement_semismallBudget_of_intrinsic
      S v t hOne hvt hChild)
  exact private_local_payment S.edges Y.position v Y.generated hNonexceptional

/-! ## Empty live-vertex base case -/

/-- If the exact live-vertex type is empty, then the defining properties of the state force the
active flag type to be empty as well.  There are no live edges, and
coordinate generation bounds the function-field transcendence degree by
zero, so the semismall budget follows without sparsity. -/
theorem FunctionFieldBranch.semismallBudget_of_card_live_eq_zero
    (S : State V Flag) (Y : FunctionFieldBranch (k := k) (K := K) S)
    (hV : Fintype.card V = 0) :
    Y.SemismallBudget S := by
  have hFlagCard : Fintype.card Flag = 0 := by
    by_contra hFlag
    have hFlagPos : 0 < Fintype.card Flag := Nat.pos_of_ne_zero hFlag
    obtain ⟨t⟩ := Fintype.card_pos_iff.mp hFlagPos
    have hTerminalBound :
        (S.terminals t).card ≤ Fintype.card V := by
      simpa using
        Finset.card_le_card (Finset.subset_univ (S.terminals t))
    rw [S.terminals_card t, hV] at hTerminalBound
    omega
  have hEdgeCard : S.edges.card = 0 := by
    by_contra hEdges
    have hEdgePos : 0 < S.edges.card := Nat.pos_of_ne_zero hEdges
    obtain ⟨e, _he⟩ := Finset.card_pos.mp hEdgePos
    have hVPos : 0 < Fintype.card V :=
      Fintype.card_pos_iff.mpr ⟨e.source⟩
    omega
  have hStress : Y.stressDim S = 0 := by
    have hStressBound :=
      directionStressDim_le_card S.edges Y.position
    unfold FunctionFieldBranch.stressDim
    omega
  have hTrdeg := Y.trdeg_le_ambient S
  unfold FunctionFieldBranch.SemismallBudget
  simpa [hStress, hFlagCard, hV] using hTrdeg

/-! ## Private strong-induction engine -/

/-- The exact recursive resource available at a state with `n` live
vertices.  It ranges over actual function fields, live types, flag types,
states, and coordinate-generated branches in the same universe levels. -/
private abbrev SmallerSemismall (k : Type u) [Field k] (n : ℕ) : Prop :=
  ∀ {K : Type v} {V : Type w} {Flag : Type x}
    [Field K] [Algebra k K]
    [Fintype V] [DecidableEq V] [Fintype Flag] [DecidableEq Flag],
    Fintype.card V < n →
      ∀ (S : State V Flag)
        (Y : FunctionFieldBranch (k := k) (K := K) S),
        S.CompletionSparse → Y.SemismallBudget S

/-- Strong induction parametrized by the two exceptional-step theorems.
The declaration is private; the public theorem supplies both parameters. -/
private theorem FunctionFieldBranch.semismallBudget_strongInduction_engine
    (hOutsideExceptional :
      ∀ {K : Type v} {V : Type w} {Flag : Type x}
        [Field K] [Algebra k K]
        [Fintype V] [DecidableEq V] [Fintype Flag] [DecidableEq Flag]
        (S : State V Flag)
        (Y : FunctionFieldBranch (k := k) (K := K) S)
        (v : V),
        S.CompletionSparse →
        S.flagMultiplicity v = 0 →
        edgeSetDegree S.edges v ≤ 3 →
        SmallerSemismall.{u, v, w, x} (k := k) (Fintype.card V) →
        OutsideExceptional (k := k) S.edges Y.position v →
        Y.SemismallBudget S)
    (hPrivateExceptional :
      ∀ {K : Type v} {V : Type w} {Flag : Type x}
        [Field K] [Algebra k K]
        [Fintype V] [DecidableEq V] [Fintype Flag] [DecidableEq Flag]
        (S : State V Flag)
        (Y : FunctionFieldBranch (k := k) (K := K) S)
        (v : V) (t : Flag),
        S.CompletionSparse →
        S.flagMultiplicity v = 1 →
        v ∈ S.terminals t →
        edgeSetDegree S.edges v ≤ 2 →
        SmallerSemismall.{u, v, w, x} (k := k) (Fintype.card V) →
        PrivateExceptional (k := k) S.edges Y.position v →
        Y.SemismallBudget S)
    (S : State V Flag) (Y : FunctionFieldBranch (k := k) (K := K) S)
    (hSparse : S.CompletionSparse) :
    Y.SemismallBudget S := by
  let P : ℕ → Prop := fun n ↦
    ∀ {K : Type v} {V : Type w} {Flag : Type x}
      [Field K] [Algebra k K]
      [Fintype V] [DecidableEq V] [Fintype Flag] [DecidableEq Flag],
      Fintype.card V = n →
        ∀ (S : State V Flag)
          (Y : FunctionFieldBranch (k := k) (K := K) S),
          S.CompletionSparse → Y.SemismallBudget S
  have hAll : ∀ n, P n := by
    intro n
    induction n using Nat.strong_induction_on with
    | h n ih =>
        dsimp only [P]
        intro K' V' Flag' _instField _instAlgebra
          _instFintypeV _instDecidableV _instFintypeFlag _instDecidableFlag
          hCard S' Y' hSparse'
        have hSmaller :
            SmallerSemismall.{u, v, w, x}
              (k := k) (Fintype.card V') := by
          intro K'' V'' Flag'' _instField'' _instAlgebra''
            _instFintypeV'' _instDecidableV''
            _instFintypeFlag'' _instDecidableFlag''
            hCardLt S'' Y'' hSparse''
          exact ih (Fintype.card V'') (by omega) rfl S'' Y'' hSparse''
        by_cases hZero : Fintype.card V' = 0
        · exact Y'.semismallBudget_of_card_live_eq_zero S' hZero
        have hVPos : 0 < Fintype.card V' := Nat.pos_of_ne_zero hZero
        obtain ⟨v₀⟩ := Fintype.card_pos_iff.mp hVPos
        have hUniverse : (Finset.univ : Finset V').Nonempty :=
          ⟨v₀, Finset.mem_univ v₀⟩
        rcases S'.exists_outside_degree_le_three_or_private_degree_le_two
            hSparse' hUniverse with hOutside | hPrivate
        · obtain ⟨v₀, hvOutside, hDegree⟩ := hOutside
          have hChildCard : Fintype.card (RemainingVertex v₀) < n := by
            have hDrop := card_remainingVertex_add_one v₀
            omega
          have hChild :
              (Y'.deleteOutsideIntrinsic S' v₀ hvOutside).SemismallBudget
                (S'.deleteOutside v₀ hvOutside) := by
            exact ih (Fintype.card (RemainingVertex v₀)) hChildCard rfl
              (S'.deleteOutside v₀ hvOutside)
              (Y'.deleteOutsideIntrinsic S' v₀ hvOutside)
              (S'.deleteOutside_completionSparse v₀ hvOutside hSparse')
          rcases outside_nonexceptional_or_exceptional
              (k := k) S'.edges Y'.position v₀ with hPaid | hExceptional
          · exact Y'.semismallBudget_of_deleteOutsideIntrinsic
              S' v₀ hvOutside hChild hPaid
          · exact hOutsideExceptional S' Y' v₀ hSparse' hvOutside hDegree
              hSmaller hExceptional
        · obtain ⟨v₀, hvPrivate, hDegree⟩ := hPrivate
          have hActive : (S'.activeFlagsAt v₀).Nonempty := by
            apply Finset.card_pos.mp
            change 0 < S'.flagMultiplicity v₀
            omega
          obtain ⟨t₀, ht₀⟩ := hActive
          have hvt : v₀ ∈ S'.terminals t₀ :=
            (S'.mem_activeFlagsAt v₀ t₀).1 ht₀
          have hChildCard : Fintype.card (RemainingVertex v₀) < n := by
            have hDrop := card_remainingVertex_add_one v₀
            omega
          have hChild :
              (Y'.deletePrivateIntrinsic S' v₀ t₀ hvPrivate hvt).SemismallBudget
                (S'.deletePrivate v₀ t₀ hvPrivate hvt) := by
            exact ih (Fintype.card (RemainingVertex v₀)) hChildCard rfl
              (S'.deletePrivate v₀ t₀ hvPrivate hvt)
              (Y'.deletePrivateIntrinsic S' v₀ t₀ hvPrivate hvt)
              (S'.deletePrivate_completionSparse
                v₀ t₀ hvPrivate hvt hSparse')
          rcases private_nonexceptional_or_exceptional
              (k := k) S'.edges Y'.position v₀ with hPaid | hExceptional
          · exact Y'.semismallBudget_of_deletePrivateIntrinsic
              S' v₀ t₀ hvPrivate hvt hChild hPaid
          · exact hPrivateExceptional S' Y' v₀ t₀ hSparse' hvPrivate hvt
              hDegree hSmaller hExceptional
  exact hAll (Fintype.card V) rfl S Y hSparse

end ProvenanceFlag

end

end RB31E2E
