import RB31EndToEnd.NullCellule.ProvenanceFlagBranch

/-!
# Provenance-flag placements over their intrinsic coordinate fields

For deletion induction it is inconvenient to replace the ambient function
field by a subtype at every step.  Instead, this file measures branch
dimension by the intermediate field generated by the current live
coordinates inside one ambient field.  Direction-stress rank is unchanged
after passing to that intrinsic field; this scalar-extension fact is proved
separately.

The original `FunctionFieldBranch` embeds into this representation, and
its generation equation identifies the intrinsic coordinate field with the
whole ambient field.  No semismallness conclusion is stored as data.
-/

namespace RB31E2E

noncomputable section

namespace ProvenanceFlag

variable {k K V Flag : Type*}
  [Field k] [Field K] [Algebra k K]
  [Fintype V] [DecidableEq V] [Fintype Flag] [DecidableEq Flag]

/-- The field intrinsically generated by the current live coordinates. -/
abbrev liveCoordinateField (a : V → Fin 3 → K) :
    IntermediateField k K :=
  IntermediateField.adjoin k (Set.range (liveCoordinateFamily a))

/-- A flagged placement in an ambient field.  Its intrinsic branch field is
`liveCoordinateField position`; no generation equation or budget is a
field of the structure. -/
structure PlacementBranch (S : State V Flag) where
  position : V → Fin 3 → K
  distinct : PairwiseDistinctOnLive position
  collinear : FlagCollinearities S position

/-- Stress dimension at the actual ambient-field placement. -/
def PlacementBranch.stressDim
    (S : State V Flag) (Y : PlacementBranch (K := K) S) : ℕ :=
  DirectionStress.directionStressDim S.edges Y.position

/-- Subtraction-free flag budget measured over the intrinsic coordinate
field. -/
def PlacementBranch.SemismallBudget
    (S : State V Flag) (Y : PlacementBranch (K := K) S) : Prop :=
  (Y.stressDim S : Cardinal) +
      Algebra.trdeg k (liveCoordinateField (k := k) Y.position) +
      2 * (Fintype.card Flag : Cardinal) ≤
    3 * (Fintype.card V : Cardinal)

/-- Forget only the redundant whole-field generation certificate. -/
def FunctionFieldBranch.toPlacement
    (S : State V Flag) (Y : FunctionFieldBranch (k := k) (K := K) S) :
    PlacementBranch (K := K) S where
  position := Y.position
  distinct := Y.distinct
  collinear := Y.collinear

@[simp]
theorem FunctionFieldBranch.toPlacement_position
    (S : State V Flag) (Y : FunctionFieldBranch (k := k) (K := K) S) :
    (Y.toPlacement S).position = Y.position := rfl

/-- On a coordinate-generated function-field branch the intrinsic and
original flag budgets are literally equivalent. -/
theorem FunctionFieldBranch.toPlacement_semismallBudget_iff
    (S : State V Flag) (Y : FunctionFieldBranch (k := k) (K := K) S) :
    PlacementBranch.SemismallBudget (k := k) S (Y.toPlacement S) ↔
      Y.SemismallBudget S := by
  rw [PlacementBranch.SemismallBudget,
    FunctionFieldBranch.SemismallBudget]
  change
    (Y.stressDim S : Cardinal) +
          Algebra.trdeg k
            (IntermediateField.adjoin k
              (Set.range (liveCoordinateFamily Y.position))) +
          2 * (Fintype.card Flag : Cardinal) ≤
        3 * (Fintype.card V : Cardinal) ↔ _
  rw [Y.generated]
  rw [(IntermediateField.topEquiv :
    (⊤ : IntermediateField k K) ≃ₐ[k] K).trdeg_eq]

/-- The intrinsic coordinate-field dimension is always bounded by the
three coordinates per live vertex. -/
theorem PlacementBranch.trdeg_le_ambient
    (S : State V Flag) (Y : PlacementBranch (K := K) S) :
    Algebra.trdeg k (liveCoordinateField (k := k) Y.position) ≤
      3 * (Fintype.card V : Cardinal) := by
  let L := liveCoordinateField (k := k) Y.position
  let x : V × Fin 3 → L := fun c ↦
    ⟨Y.position c.1 c.2,
      IntermediateField.subset_adjoin k
        (Set.range (liveCoordinateFamily Y.position)) ⟨c, rfl⟩⟩
  have hxgen : IntermediateField.adjoin k (Set.range x) = ⊤ := by
    apply top_unique
    intro y _hy
    exact IntermediateField.adjoin_induction k
      (p := fun z hz ↦
        (⟨z, hz⟩ : L) ∈ IntermediateField.adjoin k (Set.range x))
      (fun z hz ↦ by
        obtain ⟨c, rfl⟩ := hz
        exact IntermediateField.subset_adjoin k (Set.range x) ⟨c, rfl⟩)
      (fun z ↦ (IntermediateField.adjoin k (Set.range x)).algebraMap_mem z)
      (fun _ _ _ _ hx hy ↦
        (IntermediateField.adjoin k (Set.range x)).add_mem hx hy)
      (fun _ _ hx ↦
        (IntermediateField.adjoin k (Set.range x)).inv_mem hx)
      (fun _ _ _ _ hx hy ↦
        (IntermediateField.adjoin k (Set.range x)).mul_mem hx hy)
      y.property
  exact FiniteCoordinateTrdeg.trdeg_le_three_mul_card
    (k := k)
    (K := L) x hxgen

end ProvenanceFlag

end

end RB31E2E
