import RB31EndToEnd.NullCellule.VertexK4Weight

/-!
# Minimum-weight initial ideals with provenance

This file packages the minimum nonzero weighted-homogeneous component of a
polynomial as a predicate and defines the corresponding weight-initial ideal.
The definition deliberately keeps the source polynomial: membership in the
initial ideal therefore carries an explicit ideal-theoretic provenance
receipt.

The general cancellation lemma below is the algebraic core of the
edge-to-`K₃` move.  If two ideal elements have identical components below a
given weight, subtracting them exposes the first surviving component, which
is then a generator of the weight-initial ideal.  The local triangle and
vertex-to-`K₄` consequences are proved over `ℚ`, so every claimed initial
form is accompanied by an unconditional nonvanishing proof.
-/

namespace RB31E2E

namespace NullCellulePolynomial

noncomputable section

open MvPolynomial

section InitialIdeal

variable {k σ : Type*} [CommRing k]

/-- `g` is the minimum nonzero `w`-weighted homogeneous component of `f`.
The witnessing degree is retained, while all strictly smaller natural-number
components are required to vanish. -/
def IsInitialComponent (w : σ → ℕ)
    (f g : MvPolynomial σ k) : Prop :=
  ∃ d : ℕ,
    weightedHomogeneousComponent w d f = g ∧
      g ≠ 0 ∧
        ∀ e < d, weightedHomogeneousComponent w e f = 0

/-- The minimum-weight initial ideal, generated by initial components of
actual elements of `I`. -/
def weightInitialIdeal (w : σ → ℕ)
    (I : Ideal (MvPolynomial σ k)) : Ideal (MvPolynomial σ k) :=
  Ideal.span {g | ∃ f ∈ I, IsInitialComponent w f g}

/-- Every provenance-witnessed initial component is a generator of the
weight-initial ideal. -/
theorem initialComponent_mem_weightInitialIdeal
    (w : σ → ℕ) (I : Ideal (MvPolynomial σ k))
    {f g : MvPolynomial σ k} (hf : f ∈ I)
    (hfg : IsInitialComponent w f g) :
    g ∈ weightInitialIdeal w I := by
  apply Ideal.subset_span
  exact ⟨f, hf, hfg⟩

/-- A nonzero weighted-homogeneous ideal element is its own minimum-weight
initial form. -/
theorem isInitialComponent_self_of_isWeightedHomogeneous
    (w : σ → ℕ) {f : MvPolynomial σ k} {d : ℕ}
    (hf : IsWeightedHomogeneous w f d) (hf0 : f ≠ 0) :
    IsInitialComponent w f f := by
  refine ⟨d, hf.weightedHomogeneousComponent_same, hf0, ?_⟩
  intro e he
  exact hf.weightedHomogeneousComponent_ne e (Nat.ne_of_lt he)

/-- Consequently, a nonzero weighted-homogeneous member of `I` belongs to
the weight-initial ideal without changing its polynomial expression. -/
theorem isWeightedHomogeneous_mem_weightInitialIdeal
    (w : σ → ℕ) (I : Ideal (MvPolynomial σ k))
    {f : MvPolynomial σ k} {d : ℕ}
    (hfI : f ∈ I) (hf : IsWeightedHomogeneous w f d) (hf0 : f ≠ 0) :
    f ∈ weightInitialIdeal w I :=
  initialComponent_mem_weightInitialIdeal w I hfI
    (isInitialComponent_self_of_isWeightedHomogeneous w hf hf0)

/-- Weight zero has no lower component, so a nonzero zero-component is
automatically initial. -/
theorem isInitialComponent_of_component_zero
    (w : σ → ℕ) {f g : MvPolynomial σ k}
    (hfg : weightedHomogeneousComponent w 0 f = g) (hg0 : g ≠ 0) :
    IsInitialComponent w f g := by
  refine ⟨0, hfg, hg0, ?_⟩
  intro e he
  exact (Nat.not_lt_zero e he).elim

/-- Same-lower-layer cancellation: after subtracting two polynomials whose
components agree below `d`, the first specified surviving difference is an
initial component. -/
theorem isInitialComponent_sub_of_same_lower_components
    (w : σ → ℕ) {f g h : MvPolynomial σ k} {d : ℕ}
    (hd : weightedHomogeneousComponent w d f -
        weightedHomogeneousComponent w d g = h)
    (hh0 : h ≠ 0)
    (hlow : ∀ e < d,
      weightedHomogeneousComponent w e f =
        weightedHomogeneousComponent w e g) :
    IsInitialComponent w (f - g) h := by
  refine ⟨d, ?_, hh0, ?_⟩
  · simpa only [map_sub] using hd
  · intro e he
    simp only [map_sub, hlow e he, sub_self]

/-- Ideal-theoretic elimination receipt: cancelling equal low-weight layers
of two elements of `I` puts the newly exposed initial form in
`weightInitialIdeal w I`. -/
theorem cancelledInitialComponent_mem_weightInitialIdeal
    (w : σ → ℕ) (I : Ideal (MvPolynomial σ k))
    {f g h : MvPolynomial σ k} {d : ℕ}
    (hf : f ∈ I) (hg : g ∈ I)
    (hd : weightedHomogeneousComponent w d f -
        weightedHomogeneousComponent w d g = h)
    (hh0 : h ≠ 0)
    (hlow : ∀ e < d,
      weightedHomogeneousComponent w e f =
        weightedHomogeneousComponent w e g) :
    h ∈ weightInitialIdeal w I := by
  apply initialComponent_mem_weightInitialIdeal w I (I.sub_mem hf hg)
  exact isInitialComponent_sub_of_same_lower_components w hd hh0 hlow

/-- The zero ideal has zero weight-initial ideal.  This also checks that the
nonzero clause in `IsInitialComponent` rules out a spurious initial form of
the zero polynomial. -/
theorem weightInitialIdeal_bot (w : σ → ℕ) :
    weightInitialIdeal w (⊥ : Ideal (MvPolynomial σ k)) = ⊥ := by
  apply le_antisymm
  · rw [weightInitialIdeal, Ideal.span_le]
    rintro g ⟨f, hf, hfg⟩
    have hf0 : f = 0 := by simpa using hf
    subst f
    rcases hfg with ⟨d, hd, hg0, hlow⟩
    have hg : g = 0 := by simpa using hd.symm
    simp [hg]
  · exact bot_le

end InitialIdeal

/-! ## Explicit nonvanishing witnesses over `ℚ` -/

private def rationalAxis : Vec3 ℚ := ![1, 0, 0]

private def triangleAWitness : Fin 2 → Twist ℚ
  | 0 => (rationalAxis, rationalAxis)
  | 1 => 0

theorem triangleA_ne_zero : triangleA (k := ℚ) ≠ 0 := by
  intro hzero
  have heval := congrArg
    (MvPolynomial.eval (assignmentOfTwists triangleAWitness)) hzero
  have hone :
      MvPolynomial.eval (assignmentOfTwists triangleAWitness)
        (triangleA (k := ℚ)) = 1 := by
    rw [triangleA, eval_splitKlein]
    simp [triangleY, triangleAWitness, rationalAxis, Twist.splitKlein,
      Vec3.dot, Fin.sum_univ_succ]
  rw [hone] at heval
  simp at heval

private def triangleCWitness : Fin 2 → Twist ℚ
  | 0 => 0
  | 1 => (rationalAxis, rationalAxis)

theorem triangleC_ne_zero : triangleC (k := ℚ) ≠ 0 := by
  intro hzero
  have heval := congrArg
    (MvPolynomial.eval (assignmentOfTwists triangleCWitness)) hzero
  have hone :
      MvPolynomial.eval (assignmentOfTwists triangleCWitness)
        (triangleC (k := ℚ)) = 1 := by
    rw [triangleC, eval_splitKlein]
    simp [triangleD, triangleCWitness, rationalAxis, Twist.splitKlein,
      Vec3.dot, Fin.sum_univ_succ]
  rw [hone] at heval
  simp at heval

private def triangleMixedWitness : Fin 2 → Twist ℚ
  | 0 => (rationalAxis, 0)
  | 1 => (0, rationalAxis)

theorem triangleMixed_ne_zero :
    Twist.mixedPairing (triangleY (k := ℚ)) (triangleD (k := ℚ)) ≠ 0 := by
  intro hzero
  have heval := congrArg
    (MvPolynomial.eval (assignmentOfTwists triangleMixedWitness)) hzero
  have hone :
      MvPolynomial.eval (assignmentOfTwists triangleMixedWitness)
          (Twist.mixedPairing (triangleY (k := ℚ))
            (triangleD (k := ℚ))) = 1 := by
    simp [Twist.mixedPairing, triangleY, triangleD, universalTwist,
      angularCoordinate, translationalCoordinate, assignmentOfTwists,
      triangleMixedWitness, rationalAxis, Vec3.dot, Fin.sum_univ_succ]
  rw [hone] at heval
  simp at heval

/-! ## The complete edge-to-`K₃` minimum-weight table -/

/-- Provenance names for the three triangle equations
`a = q(y)`, `b = q(y+d)`, and `c = q(d)`. -/
inductive TriangleEquation
  | a
  | b
  | c
  deriving DecidableEq

/-- The polynomial carried by a named triangle equation. -/
def triangleEquationPolynomial : TriangleEquation →
    MvPolynomial (TwistVariable (Fin 2)) ℚ
  | .a => triangleA
  | .b => triangleB
  | .c => triangleC

/-- The ideal generated by a selected subset of the three local triangle
equations. -/
def triangleSelectionIdeal (S : Finset TriangleEquation) :
    Ideal (MvPolynomial (TwistVariable (Fin 2)) ℚ) :=
  Ideal.span {p | ∃ e ∈ S, triangleEquationPolynomial e = p}

theorem triangleEquation_mem_selectionIdeal
    {S : Finset TriangleEquation} {e : TriangleEquation} (he : e ∈ S) :
    triangleEquationPolynomial e ∈ triangleSelectionIdeal S := by
  apply Ideal.subset_span
  exact ⟨e, he, rfl⟩

theorem triangleA_mem_initial_of_a_selected
    {S : Finset TriangleEquation} (ha : TriangleEquation.a ∈ S) :
    triangleA (k := ℚ) ∈ weightInitialIdeal triangleWeight
      (triangleSelectionIdeal S) := by
  apply isWeightedHomogeneous_mem_weightInitialIdeal triangleWeight
    (triangleSelectionIdeal S)
  · exact triangleEquation_mem_selectionIdeal ha
  · exact triangleA_isWeightedHomogeneous_zero
  · exact triangleA_ne_zero

theorem triangleA_mem_initial_of_b_selected
    {S : Finset TriangleEquation} (hb : TriangleEquation.b ∈ S) :
    triangleA (k := ℚ) ∈ weightInitialIdeal triangleWeight
      (triangleSelectionIdeal S) := by
  apply initialComponent_mem_weightInitialIdeal triangleWeight
    (triangleSelectionIdeal S) (triangleEquation_mem_selectionIdeal hb)
  apply isInitialComponent_of_component_zero triangleWeight
  · exact triangleB_weightedComponent_zero
  · exact triangleA_ne_zero

theorem triangleC_mem_initial_of_c_selected
    {S : Finset TriangleEquation} (hc : TriangleEquation.c ∈ S) :
    triangleC (k := ℚ) ∈ weightInitialIdeal triangleWeight
      (triangleSelectionIdeal S) := by
  apply isWeightedHomogeneous_mem_weightInitialIdeal triangleWeight
    (triangleSelectionIdeal S)
  · exact triangleEquation_mem_selectionIdeal hc
  · exact triangleC_isWeightedHomogeneous_two
  · exact triangleC_ne_zero

/-- Selecting both `a` and `b` exposes the mixed weight-one receipt after
their common weight-zero layer is cancelled. -/
theorem triangleMixed_mem_initial_of_ab_selected
    {S : Finset TriangleEquation}
    (ha : TriangleEquation.a ∈ S) (hb : TriangleEquation.b ∈ S) :
    Twist.mixedPairing (triangleY (k := ℚ)) (triangleD (k := ℚ)) ∈
      weightInitialIdeal triangleWeight (triangleSelectionIdeal S) := by
  have hbI : triangleB (k := ℚ) ∈ triangleSelectionIdeal S := by
    simpa [triangleEquationPolynomial] using
      (triangleEquation_mem_selectionIdeal hb)
  have haI : triangleA (k := ℚ) ∈ triangleSelectionIdeal S := by
    simpa [triangleEquationPolynomial] using
      (triangleEquation_mem_selectionIdeal ha)
  apply cancelledInitialComponent_mem_weightInitialIdeal triangleWeight
    (triangleSelectionIdeal S) (d := 1) hbI haI
  · rw [triangleB_weightedComponent_one]
    rw [triangleA_isWeightedHomogeneous_zero.weightedHomogeneousComponent_ne
      1 (by decide)]
    simp
  · exact triangleMixed_ne_zero
  · intro e he
    have he0 : e = 0 := by omega
    subst e
    rw [triangleB_weightedComponent_zero]
    exact
      (triangleA_isWeightedHomogeneous_zero (k := ℚ)).weightedHomogeneousComponent_same.symm

/-- No selected local equation produces no initial equation. -/
theorem triangle_initial_table_none :
    weightInitialIdeal triangleWeight
      (triangleSelectionIdeal (∅ : Finset TriangleEquation)) = ⊥ := by
  rw [show triangleSelectionIdeal (∅ : Finset TriangleEquation) = ⊥ by
    simp [triangleSelectionIdeal]]
  exact weightInitialIdeal_bot triangleWeight

/-- The singleton `c` row contributes the pure displacement null equation. -/
theorem triangle_initial_table_c :
    triangleC (k := ℚ) ∈ weightInitialIdeal triangleWeight
      (triangleSelectionIdeal ({TriangleEquation.c} :
        Finset TriangleEquation)) := by
  exact triangleC_mem_initial_of_c_selected (by simp)

/-- The singleton `a` row retains the old equation. -/
theorem triangle_initial_table_a :
    triangleA (k := ℚ) ∈ weightInitialIdeal triangleWeight
      (triangleSelectionIdeal ({TriangleEquation.a} :
        Finset TriangleEquation)) := by
  exact triangleA_mem_initial_of_a_selected (by simp)

/-- The symmetric singleton `b` row has the same old weight-zero equation. -/
theorem triangle_initial_table_b :
    triangleA (k := ℚ) ∈ weightInitialIdeal triangleWeight
      (triangleSelectionIdeal ({TriangleEquation.b} :
        Finset TriangleEquation)) := by
  exact triangleA_mem_initial_of_b_selected (by simp)

/-- For the pair `{a,b}`, both the old equation and the mixed
linear-in-`d` receipt occur in the initial ideal. -/
theorem triangle_initial_table_ab :
    triangleA (k := ℚ) ∈ weightInitialIdeal triangleWeight
        (triangleSelectionIdeal
          ({TriangleEquation.a, TriangleEquation.b} :
            Finset TriangleEquation)) ∧
      Twist.mixedPairing (triangleY (k := ℚ)) (triangleD (k := ℚ)) ∈
        weightInitialIdeal triangleWeight
          (triangleSelectionIdeal
            ({TriangleEquation.a, TriangleEquation.b} :
              Finset TriangleEquation)) := by
  constructor
  · exact triangleA_mem_initial_of_a_selected (by simp)
  · exact triangleMixed_mem_initial_of_ab_selected (by simp) (by simp)

/-- The `{a,c}` representative of the “one `u`-edge plus `c`” row. -/
theorem triangle_initial_table_ac :
    triangleA (k := ℚ) ∈ weightInitialIdeal triangleWeight
        (triangleSelectionIdeal
          ({TriangleEquation.a, TriangleEquation.c} :
            Finset TriangleEquation)) ∧
      triangleC (k := ℚ) ∈ weightInitialIdeal triangleWeight
        (triangleSelectionIdeal
          ({TriangleEquation.a, TriangleEquation.c} :
            Finset TriangleEquation)) := by
  constructor
  · exact triangleA_mem_initial_of_a_selected (by simp)
  · exact triangleC_mem_initial_of_c_selected (by simp)

/-- The symmetric `{b,c}` representative has the same old/local initial
equations. -/
theorem triangle_initial_table_bc :
    triangleA (k := ℚ) ∈ weightInitialIdeal triangleWeight
        (triangleSelectionIdeal
          ({TriangleEquation.b, TriangleEquation.c} :
            Finset TriangleEquation)) ∧
      triangleC (k := ℚ) ∈ weightInitialIdeal triangleWeight
        (triangleSelectionIdeal
          ({TriangleEquation.b, TriangleEquation.c} :
            Finset TriangleEquation)) := by
  constructor
  · exact triangleA_mem_initial_of_b_selected (by simp)
  · exact triangleC_mem_initial_of_c_selected (by simp)

/-- The full `{a,b,c}` row contains the old equation, the pure displacement
null equation, and the mixed incidence receipt. -/
theorem triangle_initial_table_abc :
    triangleA (k := ℚ) ∈ weightInitialIdeal triangleWeight
        (triangleSelectionIdeal
          ({TriangleEquation.a, TriangleEquation.b, TriangleEquation.c} :
            Finset TriangleEquation)) ∧
      triangleC (k := ℚ) ∈ weightInitialIdeal triangleWeight
        (triangleSelectionIdeal
          ({TriangleEquation.a, TriangleEquation.b, TriangleEquation.c} :
            Finset TriangleEquation)) ∧
      Twist.mixedPairing (triangleY (k := ℚ)) (triangleD (k := ℚ)) ∈
        weightInitialIdeal triangleWeight
          (triangleSelectionIdeal
            ({TriangleEquation.a, TriangleEquation.b, TriangleEquation.c} :
              Finset TriangleEquation)) := by
  constructor
  · exact triangleA_mem_initial_of_a_selected (by simp)
  constructor
  · exact triangleC_mem_initial_of_c_selected (by simp)
  · exact triangleMixed_mem_initial_of_ab_selected (by simp) (by simp)

/-! ## Vertex-to-`K₄` initial-ideal receipts -/

private def vertexK4OldWitness : VertexK4Label → Twist ℚ
  | .center => (rationalAxis, rationalAxis)
  | .external => 0
  | .displacement _ => 0

theorem vertexK4OldExternal_ne_zero :
    vertexK4OldExternal (k := ℚ) ≠ 0 := by
  intro hzero
  have heval := congrArg
    (MvPolynomial.eval (assignmentOfTwists vertexK4OldWitness)) hzero
  have hone :
      MvPolynomial.eval (assignmentOfTwists vertexK4OldWitness)
        (vertexK4OldExternal (k := ℚ)) = 1 := by
    rw [vertexK4OldExternal, eval_splitKlein, evalPolynomialTwist_sub]
    simp [vertexK4Z, vertexK4A, vertexK4OldWitness, rationalAxis,
      Twist.splitKlein, Vec3.dot, Fin.sum_univ_succ]
  rw [hone] at heval
  simp at heval

theorem vertexK4InternalClone_ne_zero {i j : Fin 3} (hij : i ≠ j) :
    vertexK4InternalClone (k := ℚ) i j ≠ 0 := by
  let Y : VertexK4Label → Twist ℚ := fun label ↦
    if label = VertexK4Label.displacement i then
      (rationalAxis, rationalAxis)
    else 0
  intro hzero
  have heval := congrArg (MvPolynomial.eval (assignmentOfTwists Y)) hzero
  have hone :
      MvPolynomial.eval (assignmentOfTwists Y)
        (vertexK4InternalClone (k := ℚ) i j) = 1 := by
    rw [vertexK4InternalClone_eq_internalDisplacement,
      vertexK4InternalDisplacement, eval_splitKlein,
      evalPolynomialTwist_sub]
    simp [vertexK4D, Y, Ne.symm hij, rationalAxis, Twist.splitKlein, Vec3.dot,
      Fin.sum_univ_succ]
  rw [hone] at heval
  simp at heval

/-- Any ideal containing an external clone-edge equation has the contracted
old external equation in its weight-initial ideal. -/
theorem vertexK4OldExternal_mem_initial_of_externalClone_mem
    (I : Ideal (MvPolynomial (TwistVariable VertexK4Label) ℚ))
    (i : Fin 3) (hi : vertexK4ExternalClone (k := ℚ) i ∈ I) :
    vertexK4OldExternal (k := ℚ) ∈
      weightInitialIdeal vertexK4Weight I := by
  apply initialComponent_mem_weightInitialIdeal vertexK4Weight I hi
  apply isInitialComponent_of_component_zero vertexK4Weight
  · exact vertexK4ExternalClone_weightedComponent_zero i
  · exact vertexK4OldExternal_ne_zero

/-- A genuine internal clone edge (`i ≠ j`) is purely of weight two and
therefore enters the initial ideal unchanged. -/
theorem vertexK4InternalClone_mem_initial_of_mem
    (I : Ideal (MvPolynomial (TwistVariable VertexK4Label) ℚ))
    {i j : Fin 3} (hij : i ≠ j)
    (hijI : vertexK4InternalClone (k := ℚ) i j ∈ I) :
    vertexK4InternalClone (k := ℚ) i j ∈
      weightInitialIdeal vertexK4Weight I := by
  apply isWeightedHomogeneous_mem_weightInitialIdeal vertexK4Weight I hijI
  · exact vertexK4InternalClone_isWeightedHomogeneous_two i j
  · exact vertexK4InternalClone_ne_zero hij

/-- Principal-ideal form of the external-edge contraction receipt. -/
theorem vertexK4_external_principal_initial (i : Fin 3) :
    vertexK4OldExternal (k := ℚ) ∈
      weightInitialIdeal vertexK4Weight
        (Ideal.span ({vertexK4ExternalClone (k := ℚ) i} :
          Set (MvPolynomial (TwistVariable VertexK4Label) ℚ))) := by
  apply vertexK4OldExternal_mem_initial_of_externalClone_mem (i := i)
  exact Ideal.subset_span (by simp)

/-- Principal-ideal form of the pure weight-two internal-edge receipt. -/
theorem vertexK4_internal_principal_initial
    {i j : Fin 3} (hij : i ≠ j) :
    vertexK4InternalClone (k := ℚ) i j ∈
      weightInitialIdeal vertexK4Weight
        (Ideal.span ({vertexK4InternalClone (k := ℚ) i j} :
          Set (MvPolynomial (TwistVariable VertexK4Label) ℚ))) := by
  apply vertexK4InternalClone_mem_initial_of_mem _ hij
  exact Ideal.subset_span (by simp)

end

end NullCellulePolynomial

end RB31E2E
