import RB31EndToEnd.Linear.DirectionResponse
import RB31EndToEnd.Linear.FiniteFamilyBaseChange

/-!
# Direction-stress dimension under field extension

The provenance induction projects a generic configuration to the field
generated by the retained coordinates.  Its child direction rows are
therefore first defined over that smaller field and then viewed over the
parent function field.  This file proves, from the literal row formulas,
that row rank and hence stress dimension are unchanged by this scalar
extension.
-/

namespace RB31E2E

namespace DirectionStress

noncomputable section

variable {L K V : Type*}
  [Field L] [Field K] [Algebra L K]
  [Fintype V] [DecidableEq V]

/-- Coordinatewise scalar extension of a placement. -/
def mapPlacement (a : V → Fin 3 → L) : V → Fin 3 → K :=
  fun v j ↦ algebraMap L K (a v j)

/-- Flatten vertex and spatial coordinates into a single finite function
space.  This is the representation consumed by the finite-family
base-change theorem. -/
def flattenVector (x : V → Fin 3 → L) : V × Fin 3 → L :=
  fun p ↦ x p.1 p.2

omit [Fintype V] [DecidableEq V] in
/-- Currying is a linear equivalence, so flattening a finite row family does
not change the dimension of its span. -/
theorem finrank_span_flatten
    {I : Type*} [Finite I] (row : I → V → Fin 3 → L) :
    Module.finrank L (Submodule.span L (Set.range row)) =
      Module.finrank L
        (Submodule.span L (Set.range (fun i ↦ flattenVector (row i)))) := by
  let flat : (V → Fin 3 → L) ≃ₗ[L] (V × Fin 3 → L) :=
    (LinearEquiv.curry L L V (Fin 3)).symm
  have hset :
      flat '' Set.range row =
        Set.range (fun i ↦ flattenVector (row i)) := by
    ext x
    constructor
    · rintro ⟨y, ⟨i, rfl⟩, rfl⟩
      exact ⟨i, rfl⟩
    · rintro ⟨i, rfl⟩
      exact ⟨row i, ⟨i, rfl⟩, rfl⟩
  have hspan :
      (Submodule.span L (Set.range row)).map
          (flat : (V → Fin 3 → L) →ₗ[L] (V × Fin 3 → L)) =
        Submodule.span L
          (Set.range (fun i ↦ flattenVector (row i))) := by
    rw [Submodule.map_span]
    change Submodule.span L (flat '' Set.range row) = _
    rw [hset]
  calc
    Module.finrank L (Submodule.span L (Set.range row)) =
        Module.finrank L
          ((Submodule.span L (Set.range row)).map
            (flat : (V → Fin 3 → L) →ₗ[L] (V × Fin 3 → L))) := by
      symm
      exact LinearEquiv.finrank_map_eq flat _
    _ = Module.finrank L
        (Submodule.span L
          (Set.range (fun i ↦ flattenVector (row i)))) := by
      rw [hspan]

omit [Fintype V] in
/-- A direction row is transported coordinatewise by scalar extension. -/
theorem directionRow_mapPlacement
    (a : V → Fin 3 → L) (e : SimpleEdge V) :
    flattenVector (directionRow (mapPlacement (K := K) a) e) =
      FiniteFamilyBaseChange.mapVector (K := K)
        (flattenVector (directionRow a e)) := by
  funext p
  rcases p with ⟨v, j⟩
  simp only [directionRow, edgeDirection, mapPlacement,
    flattenVector, FiniteFamilyBaseChange.mapVector, Function.comp_apply]
  split_ifs <;> simp

/-- Direction-row rank is invariant under a field extension. -/
theorem directionEquilibriumRank_mapPlacement
    (F : SimpleEdgeSet V) (a : V → Fin 3 → L) :
    directionEquilibriumRank F (mapPlacement (K := K) a) =
      directionEquilibriumRank F a := by
  rw [directionEquilibriumRank_eq_finrank_span_rows,
    directionEquilibriumRank_eq_finrank_span_rows]
  rw [finrank_span_flatten, finrank_span_flatten]
  have hbase := FiniteFamilyBaseChange.finrank_span_range_mapVector_finite
    (K := K) (fun e : F ↦ flattenVector (directionRow a e.1))
  rw [hbase]
  have hset :
      Set.range (fun e : F ↦
        FiniteFamilyBaseChange.mapVector (K := K)
          (flattenVector (directionRow a e.1))) =
        Set.range (fun e : F ↦
          flattenVector (directionRow (mapPlacement (K := K) a) e.1)) := by
    ext x
    constructor <;> rintro ⟨e, rfl⟩
    · exact ⟨e, directionRow_mapPlacement (K := K) a e.1⟩
    · exact ⟨e, directionRow_mapPlacement (K := K) a e.1 |>.symm⟩
  rw [hset]

/-- Direction-stress nullity is invariant under a field extension. -/
theorem directionStressDim_mapPlacement
    (F : SimpleEdgeSet V) (a : V → Fin 3 → L) :
    directionStressDim F (mapPlacement (K := K) a) =
      directionStressDim F a := by
  have hK := directionStressDim_add_directionEquilibriumRank
    F (mapPlacement (K := K) a)
  have hL := directionStressDim_add_directionEquilibriumRank F a
  rw [directionEquilibriumRank_mapPlacement] at hK
  omega

end

end DirectionStress

end RB31E2E
