import RB31EndToEnd.Linear.DirectionResponse
import RB31EndToEnd.Algebra.CoordinateFieldTower

/-!
# The three-coordinate payment ledger for an outside deletion

Deleting one outside live vertex creates two actual local quantities:

* `u`, the finite dimension of the kernel of the direction-response
  connecting map;
* `d`, the transcendence degree of the full function field over the field
  generated by the retained coordinates.

The new point has exactly three coordinate functions, hence `d ≤ 3`.  In
the nonexceptional branch the response kernel has dimension at most the
remaining coordinate budget `3-d`; this transparent linear/function-field
gate gives the required payment `u+d ≤3`.  The exceptional alternative is
kept as the literal negation of this gate and is not stored in any graph or
branch structure.
-/

namespace RB31E2E

namespace DirectionStress

noncomputable section

universe u v w

variable {k : Type u} {K : Type v} {V : Type w}
  [Field k] [Field K] [Algebra k K]
  [Fintype V] [DecidableEq V]

/-- The retained coordinate labels after deleting `v`. -/
abbrev RetainedCoordinate (v : V) := AwayFrom v × Fin 3

/-- The three coordinate labels of the deleted point. -/
abbrev DeletedCoordinate := Fin 3

/-- Retained live-coordinate family inside the ambient function field. -/
def retainedCoordinates (a : V → Fin 3 → K) (v : V) :
    RetainedCoordinate v → K :=
  fun c ↦ a c.1.1 c.2

/-- The three coordinate functions of the deleted point. -/
def deletedCoordinates (a : V → Fin 3 → K) (v : V) :
    DeletedCoordinate → K :=
  fun j ↦ a v j

/-- The intermediate function field generated by retained coordinates. -/
abbrev retainedCoordinateField (a : V → Fin 3 → K) (v : V) :
    IntermediateField k K :=
  CoordinateFieldTower.oldCoordinateField
    (k := k) (K := K) (retainedCoordinates a v)

/-- The actual transcendence-degree cost of adjoining the deleted point. -/
def outsideExtensionTrdeg (a : V → Fin 3 → K) (v : V) : Cardinal :=
  Algebra.trdeg (retainedCoordinateField (k := k) a v) K

/-- The actual local stress increment furnished by the deletion exact
sequence. -/
def outsideResponseKernelDim
    (F : SimpleEdgeSet V) (a : V → Fin 3 → K) (v : V) : ℕ :=
  Module.finrank K
    (LinearMap.ker
      (deletedConnectingClass F a v))

/-- The local response dimension is exactly the second summand in the
kernel-exact deletion formula. -/
theorem directionStressDim_eq_delete_add_outsideResponseKernelDim
    (F : SimpleEdgeSet V) (a : V → Fin 3 → K) (v : V) :
    directionStressDim F a =
      directionStressDim (deleteVertexEdges F v) a +
        outsideResponseKernelDim F a v := by
  exact directionStressDim_delete_add_connectingKernel F a v

/-- Reindex all live coordinates as retained coordinates or one of the
three coordinates at `v`. -/
def liveCoordinateDeletionEquiv (v : V) :
    V × Fin 3 ≃ RetainedCoordinate v ⊕ DeletedCoordinate where
  toFun c := if hcv : c.1 = v then Sum.inr c.2 else Sum.inl (⟨c.1, hcv⟩, c.2)
  invFun c := match c with
    | Sum.inl c => (c.1.1, c.2)
    | Sum.inr j => (v, j)
  left_inv c := by
    by_cases hcv : c.1 = v
    · apply Prod.ext
      · simp [hcv]
      · simp [hcv]
    · simp [hcv]
  right_inv c := by
    cases c with
    | inl c => simp [c.1.2]
    | inr j => simp

omit [Fintype V] in
/-- Generation by all live coordinates is equivalent to generation by the
union of retained and deleted coordinate ranges. -/
theorem adjoin_retained_union_deleted_eq_top
    (a : V → Fin 3 → K) (v : V)
    (hgen : IntermediateField.adjoin k
      (Set.range (fun c : V × Fin 3 ↦ a c.1 c.2)) = ⊤) :
    IntermediateField.adjoin k
      (Set.range (retainedCoordinates a v) ∪
        Set.range (deletedCoordinates a v)) = ⊤ := by
  have hRange :
      Set.range (fun c : V × Fin 3 ↦ a c.1 c.2) =
        Set.range (retainedCoordinates a v) ∪
          Set.range (deletedCoordinates a v) := by
    ext x
    constructor
    · rintro ⟨c, rfl⟩
      by_cases hcv : c.1 = v
      · exact Or.inr ⟨c.2, by simp [hcv, deletedCoordinates]⟩
      · exact Or.inl ⟨(⟨c.1, hcv⟩, c.2), rfl⟩
    · rintro (hOld | hNew)
      · obtain ⟨c, rfl⟩ := hOld
        exact ⟨(c.1.1, c.2), rfl⟩
      · obtain ⟨j, rfl⟩ := hNew
        exact ⟨(v, j), rfl⟩
  rw [← hRange]
  exact hgen

omit [Fintype V] in
/-- The extension created by one deleted point has transcendence degree at
most three. -/
theorem outsideExtensionTrdeg_le_three
    (a : V → Fin 3 → K) (v : V)
    (hgen : IntermediateField.adjoin k
      (Set.range (fun c : V × Fin 3 ↦ a c.1 c.2)) = ⊤) :
    outsideExtensionTrdeg (k := k) a v ≤ 3 := by
  have hUnion := adjoin_retained_union_deleted_eq_top
    (k := k) a v hgen
  simpa [outsideExtensionTrdeg, retainedCoordinateField] using
    (CoordinateFieldTower.extension_trdeg_le_card
      (k := k) (K := K)
      (retainedCoordinates a v) (deletedCoordinates a v) hUnion)

omit [Fintype V] in
/-- The extension transcendence degree is finite; this legitimizes its
`Cardinal.toNat` use in the local numerical ledger. -/
theorem outsideExtensionTrdeg_lt_aleph0
    (a : V → Fin 3 → K) (v : V)
    (hgen : IntermediateField.adjoin k
      (Set.range (fun c : V × Fin 3 ↦ a c.1 c.2)) = ⊤) :
    outsideExtensionTrdeg (k := k) a v < Cardinal.aleph0 := by
  exact (outsideExtensionTrdeg_le_three (k := k) a v hgen).trans_lt
    Cardinal.natCast_lt_aleph0

/-- Transparent nonexceptional gate: the response-kernel dimension fits
inside the three-coordinate budget left after the extension transcendence
degree is paid. -/
def OutsideNonexceptional
    (F : SimpleEdgeSet V) (a : V → Fin 3 → K) (v : V) : Prop :=
  outsideResponseKernelDim F a v +
      (outsideExtensionTrdeg (k := k) a v).toNat ≤ 3

/-- The exceptional branch is literally the failure of the local payment
gate, not a stored tag. -/
def OutsideExceptional
    (F : SimpleEdgeSet V) (a : V → Fin 3 → K) (v : V) : Prop :=
  ¬ OutsideNonexceptional (k := k) F a v

omit [Fintype V] in
/-- The outside local payment in natural-number form. -/
theorem outside_local_payment_toNat
    (F : SimpleEdgeSet V) (a : V → Fin 3 → K) (v : V)
    (hNonexceptional : OutsideNonexceptional (k := k) F a v) :
    outsideResponseKernelDim F a v +
        (outsideExtensionTrdeg (k := k) a v).toNat ≤ 3 :=
  hNonexceptional

omit [Fintype V] in
/-- The desired cardinal-valued payment: local stress growth plus function-
field growth costs at most the three coordinates of the deleted point. -/
theorem outside_local_payment
    (F : SimpleEdgeSet V) (a : V → Fin 3 → K) (v : V)
    (hgen : IntermediateField.adjoin k
      (Set.range (fun c : V × Fin 3 ↦ a c.1 c.2)) = ⊤)
    (hNonexceptional : OutsideNonexceptional (k := k) F a v) :
    (outsideResponseKernelDim F a v : Cardinal) +
        outsideExtensionTrdeg (k := k) a v ≤ 3 := by
  have hfinite := outsideExtensionTrdeg_lt_aleph0 (k := k) a v hgen
  rw [← Cardinal.cast_toNat_of_lt_aleph0 hfinite]
  exact_mod_cast hNonexceptional

omit [Fintype V] in
/-- Every local outside configuration is transparently split into the paid
branch and its exceptional complement. -/
theorem outside_nonexceptional_or_exceptional
    (F : SimpleEdgeSet V) (a : V → Fin 3 → K) (v : V) :
    OutsideNonexceptional (k := k) F a v ∨
      OutsideExceptional (k := k) F a v := by
  exact em _

omit [Fintype V] [DecidableEq V] in
/-- Coefficient-comparison gate for the genuinely maximal extension case:
if the three new coordinates generate the extension and its trdeg is at
least three, then those coordinates are algebraically independent over the
retained field. -/
theorem deletedCoordinates_algebraicIndependent_of_three_le_trdeg
    (a : V → Fin 3 → K) (v : V)
    (hgen : IntermediateField.adjoin k
      (Set.range (retainedCoordinates a v) ∪
        Set.range (deletedCoordinates a v)) = ⊤)
    (hThree : (3 : Cardinal) ≤ outsideExtensionTrdeg (k := k) a v) :
    AlgebraicIndependent (retainedCoordinateField (k := k) a v)
      (deletedCoordinates a v) := by
  apply FiniteCoordinateTrdeg.algebraicIndependent_of_card_le_trdeg_of_adjoin_range_eq_top
    (deletedCoordinates a v)
  · exact CoordinateFieldTower.adjoin_new_over_old_eq_top
      (k := k) (retainedCoordinates a v) (deletedCoordinates a v) hgen
  · simpa [outsideExtensionTrdeg] using hThree

end

end DirectionStress

end RB31E2E
