import RB31EndToEnd.Linear.OutsideLocalClassification
import RB31EndToEnd.Incidence.CollinearityPolynomial

/-!
# Geometry and function-field cost of a low-degree outside star

This file supplies the geometric half of the outside-local classification.
The argument is carried out on the literal direction columns and the actual
retained-coordinate intermediate field:

* rank one puts the apex on a line through two retained neighbours, hence
  the coordinate extension has transcendence degree at most one;
* rank two with three noncollinear retained neighbours puts the apex in
  their affine plane, hence the extension has transcendence degree at most
  two.

Together with `OutsideLocalClassification`, these two field-generation
statements eliminate every failed-payment branch except the genuine
degree-three/full-fibre/collinear-neighbour branch.
-/

namespace RB31E2E

namespace DirectionStress

noncomputable section

universe u v w x

variable {k : Type u} {K : Type v} {V : Type w}
  [Field k] [Field K] [Algebra k K]
  [Fintype V] [DecidableEq V]

/-! ## Finite generators for a constrained point -/

omit [Fintype V] [DecidableEq V] in
/-- If the three coordinates of a point generate an extension and all lie
in a field generated by `r` parameters, its transcendence degree is at most
`r`. -/
theorem trdeg_le_card_of_coordinates_mem_parameter_adjoin
    {L : IntermediateField k K} {I : Type x} [Fintype I]
    (point : Fin 3 → K) (parameter : I → K)
    (hPointGen : IntermediateField.adjoin L (Set.range point) = ⊤)
    (hmem : ∀ j, point j ∈
      IntermediateField.adjoin L (Set.range parameter)) :
    Algebra.trdeg L K ≤ (Fintype.card I : Cardinal) := by
  have hParameterGen :
      IntermediateField.adjoin L (Set.range parameter) = ⊤ := by
    apply top_unique
    rw [← hPointGen]
    exact IntermediateField.adjoin_le_iff.mpr (by
      rintro _ ⟨j, rfl⟩
      exact hmem j)
  exact FiniteCoordinateTrdeg.trdeg_le_card_of_adjoin_range_eq_top
    parameter hParameterGen

omit [Fintype V] [DecidableEq V] in
/-- Every retained coordinate is an element of the literal retained
coordinate field. -/
theorem retained_coordinate_mem
    (a : V → Fin 3 → K) (v p : V) (hp : p ≠ v) (j : Fin 3) :
    a p j ∈ retainedCoordinateField (k := k) a v := by
  apply IntermediateField.subset_adjoin
  exact ⟨(⟨p, hp⟩, j), rfl⟩

omit [Fintype V] in
/-- If the apex lies on a line through two retained points, one scalar
parameter generates all three apex coordinates. -/
theorem outsideExtensionTrdeg_le_one_of_line_parameter
    (a : V → Fin 3 → K) (v p q : V)
    (hp : p ≠ v) (hq : q ≠ v)
    (hgen : IntermediateField.adjoin k
      (Set.range (fun c : V × Fin 3 ↦ a c.1 c.2)) = ⊤)
    (hline : ∃ s : K, a v = a p + s • (a q - a p)) :
    outsideExtensionTrdeg (k := k) a v ≤ 1 := by
  obtain ⟨s, hs⟩ := hline
  let L : IntermediateField k K := retainedCoordinateField (k := k) a v
  let parameter : Fin 1 → K := fun _ ↦ s
  have hPointGen :
      IntermediateField.adjoin L (Set.range (deletedCoordinates a v)) = ⊤ := by
    exact CoordinateFieldTower.adjoin_new_over_old_eq_top
      (k := k) (retainedCoordinates a v) (deletedCoordinates a v)
      (adjoin_retained_union_deleted_eq_top (k := k) a v hgen)
  have hmem : ∀ j, deletedCoordinates a v j ∈
      IntermediateField.adjoin L (Set.range parameter) := by
    intro j
    let M : IntermediateField L K :=
      IntermediateField.adjoin L (Set.range parameter)
    have hpM : a p j ∈ M := by
      exact IntermediateField.algebraMap_mem M
        (⟨a p j, retained_coordinate_mem (k := k) a v p hp j⟩ : L)
    have hqM : a q j ∈ M := by
      exact IntermediateField.algebraMap_mem M
        (⟨a q j, retained_coordinate_mem (k := k) a v q hq j⟩ : L)
    have hsM : s ∈ M := by
      apply IntermediateField.subset_adjoin
      exact ⟨0, rfl⟩
    have hj := congrFun hs j
    change a v j ∈ M
    rw [hj]
    simpa only [Pi.add_apply, Pi.sub_apply, Pi.smul_apply, smul_eq_mul] using
      M.add_mem hpM (M.mul_mem hsM (M.sub_mem hqM hpM))
  simpa [outsideExtensionTrdeg, L] using
    (trdeg_le_card_of_coordinates_mem_parameter_adjoin
      (k := k) (L := L) (deletedCoordinates a v) parameter hPointGen hmem)

omit [Fintype V] in
/-- If the apex lies in the affine plane of three retained points, two
scalar parameters generate all three apex coordinates. -/
theorem outsideExtensionTrdeg_le_two_of_plane_parameters
    (a : V → Fin 3 → K) (v p q r : V)
    (hp : p ≠ v) (hq : q ≠ v) (hr : r ≠ v)
    (hgen : IntermediateField.adjoin k
      (Set.range (fun c : V × Fin 3 ↦ a c.1 c.2)) = ⊤)
    (hplane : ∃ s t : K,
      a v = a p + s • (a q - a p) + t • (a r - a p)) :
    outsideExtensionTrdeg (k := k) a v ≤ 2 := by
  obtain ⟨s, t, hst⟩ := hplane
  let L : IntermediateField k K := retainedCoordinateField (k := k) a v
  let parameter : Fin 2 → K := ![s, t]
  have hPointGen :
      IntermediateField.adjoin L (Set.range (deletedCoordinates a v)) = ⊤ := by
    exact CoordinateFieldTower.adjoin_new_over_old_eq_top
      (k := k) (retainedCoordinates a v) (deletedCoordinates a v)
      (adjoin_retained_union_deleted_eq_top (k := k) a v hgen)
  have hmem : ∀ j, deletedCoordinates a v j ∈
      IntermediateField.adjoin L (Set.range parameter) := by
    intro j
    let M : IntermediateField L K :=
      IntermediateField.adjoin L (Set.range parameter)
    have hpM : a p j ∈ M := by
      exact IntermediateField.algebraMap_mem M
        (⟨a p j, retained_coordinate_mem (k := k) a v p hp j⟩ : L)
    have hqM : a q j ∈ M := by
      exact IntermediateField.algebraMap_mem M
        (⟨a q j, retained_coordinate_mem (k := k) a v q hq j⟩ : L)
    have hrM : a r j ∈ M := by
      exact IntermediateField.algebraMap_mem M
        (⟨a r j, retained_coordinate_mem (k := k) a v r hr j⟩ : L)
    have hsM : s ∈ M := by
      apply IntermediateField.subset_adjoin
      exact ⟨0, rfl⟩
    have htM : t ∈ M := by
      apply IntermediateField.subset_adjoin
      exact ⟨1, rfl⟩
    have hj := congrFun hst j
    change a v j ∈ M
    rw [hj]
    simpa only [Pi.add_apply, Pi.sub_apply, Pi.smul_apply, smul_eq_mul] using
      M.add_mem
        (M.add_mem hpM (M.mul_mem hsM (M.sub_mem hqM hpM)))
        (M.mul_mem htM (M.sub_mem hrM hpM))
  simpa [outsideExtensionTrdeg, L] using
    (trdeg_le_card_of_coordinates_mem_parameter_adjoin
      (k := k) (L := L) (deletedCoordinates a v) parameter hPointGen hmem)

/-! ## Literal direction columns at named neighbours -/

omit [Fintype V] in
/-- The direction row of the unordered edge `{v,p}`, evaluated at `v`, is
the orientation-free difference `a v - a p`. -/
theorem directionRow_simpleEdge_at_left
    (a : V → Fin 3 → K) (v p : V) (hvp : v ≠ p) :
    directionRow a (simpleEdge v p hvp) v = a v - a p := by
  let e : SimpleEdge V := simpleEdge v p hvp
  have hEnds :
      (e.source = v ∧ e.target = p) ∨
        (e.source = p ∧ e.target = v) := by
    have hPair : s(e.source, e.target) = s(v, p) := by
      rw [e.source_target_mk]
      rfl
    exact Sym2.eq_iff.mp hPair
  rcases hEnds with ⟨hsource, htarget⟩ | ⟨hsource, htarget⟩
  · calc
      directionRow a e v = directionRow a e e.source := by rw [hsource]
      _ = edgeDirection a e := directionRow_source a e
      _ = a v - a p := by
        funext j
        simp [edgeDirection, hsource, htarget]
  · calc
      directionRow a e v = directionRow a e e.target := by rw [htarget]
      _ = -(edgeDirection a e) := directionRow_target a e
      _ = a v - a p := by
        funext j
        simp [edgeDirection, hsource, htarget]

omit [Fintype V] in
/-- Every named neighbour difference is a literal vector in the range of
the local equilibrium map. -/
theorem namedNeighbourDifference_mem_localRange
    (F : SimpleEdgeSet V) (a : V → Fin 3 → K) (v p : V)
    (hvp : v ≠ p) (hEdge : simpleEdge v p hvp ∈ F) :
    a v - a p ∈ LinearMap.range (localEquilibriumAt F a v) := by
  let e : incidentEdges F v :=
    ⟨simpleEdge v p hvp,
      mem_incidentEdges.mpr ⟨hEdge, by rw [vertices_simpleEdge]; simp⟩⟩
  refine ⟨Pi.single e 1, ?_⟩
  rw [localEquilibriumAt_piSingle, one_smul]
  exact directionRow_simpleEdge_at_left a v p hvp

/-- Explicit, pairwise-distinct neighbours exhausting a degree-three
incidence packet. -/
structure DegreeThreeNeighbours (F : SimpleEdgeSet V) (v : V) where
  p : V
  q : V
  r : V
  hvp : v ≠ p
  hvq : v ≠ q
  hvr : v ≠ r
  hpq : p ≠ q
  hpr : p ≠ r
  hqr : q ≠ r
  vp_mem : simpleEdge v p hvp ∈ F
  vq_mem : simpleEdge v q hvq ∈ F
  vr_mem : simpleEdge v r hvr ∈ F

/-- Two named distinct neighbours of one vertex. -/
structure TwoNeighbours (F : SimpleEdgeSet V) (v : V) where
  p : V
  q : V
  hvp : v ≠ p
  hvq : v ≠ q
  hpq : p ≠ q
  vp_mem : simpleEdge v p hvp ∈ F
  vq_mem : simpleEdge v q hvq ∈ F

omit [Fintype V] in
/-- A degree-three simple incidence set produces three actual, distinct
neighbours; this is only an enumeration theorem, not a stored geometric
classification. -/
theorem exists_degreeThreeNeighbours
    (F : SimpleEdgeSet V) (v : V) (hDegree : edgeSetDegree F v = 3) :
    Nonempty (DegreeThreeNeighbours F v) := by
  have hIncidentCard : (incidentEdges F v).card = 3 := hDegree
  obtain ⟨e₁, e₂, e₃, he₁₂, he₁₃, he₂₃, hIncidentEq⟩ :=
    Finset.card_eq_three.mp hIncidentCard
  have he₁ : e₁ ∈ incidentEdges F v := by rw [hIncidentEq]; simp
  have he₂ : e₂ ∈ incidentEdges F v := by rw [hIncidentEq]; simp
  have he₃ : e₃ ∈ incidentEdges F v := by rw [hIncidentEq]; simp
  obtain ⟨p, hvp, hpEdge⟩ :=
    exists_otherEndpoint e₁ (mem_incidentEdges.mp he₁).2
  obtain ⟨q, hvq, hqEdge⟩ :=
    exists_otherEndpoint e₂ (mem_incidentEdges.mp he₂).2
  obtain ⟨r, hvr, hrEdge⟩ :=
    exists_otherEndpoint e₃ (mem_incidentEdges.mp he₃).2
  have hpq : p ≠ q := by
    intro hpq
    subst q
    apply he₁₂
    calc
      e₁ = simpleEdge v p hvp := hpEdge
      _ = simpleEdge v p hvq := by rfl
      _ = e₂ := hqEdge.symm
  have hpr : p ≠ r := by
    intro hpr
    subst r
    apply he₁₃
    calc
      e₁ = simpleEdge v p hvp := hpEdge
      _ = simpleEdge v p hvr := by rfl
      _ = e₃ := hrEdge.symm
  have hqr : q ≠ r := by
    intro hqr
    subst r
    apply he₂₃
    calc
      e₂ = simpleEdge v q hvq := hqEdge
      _ = simpleEdge v q hvr := by rfl
      _ = e₃ := hrEdge.symm
  refine ⟨{
    p := p, q := q, r := r,
    hvp := hvp, hvq := hvq, hvr := hvr,
    hpq := hpq, hpr := hpr, hqr := hqr,
    vp_mem := ?_, vq_mem := ?_, vr_mem := ?_ }⟩
  · rw [← hpEdge]
    exact (mem_incidentEdges.mp he₁).1
  · rw [← hqEdge]
    exact (mem_incidentEdges.mp he₂).1
  · rw [← hrEdge]
    exact (mem_incidentEdges.mp he₃).1

omit [Fintype V] in
/-- Exactly two incident edges similarly give two actual distinct
neighbours. -/
theorem exists_degreeTwoNeighbours
    (F : SimpleEdgeSet V) (v : V) (hDegree : edgeSetDegree F v = 2) :
    Nonempty (TwoNeighbours F v) := by
  have hIncidentCard : (incidentEdges F v).card = 2 := hDegree
  obtain ⟨e₁, e₂, he₁₂, hIncidentEq⟩ :=
    Finset.card_eq_two.mp hIncidentCard
  have he₁ : e₁ ∈ incidentEdges F v := by rw [hIncidentEq]; simp
  have he₂ : e₂ ∈ incidentEdges F v := by rw [hIncidentEq]; simp
  obtain ⟨p, hvp, hpEdge⟩ :=
    exists_otherEndpoint e₁ (mem_incidentEdges.mp he₁).2
  obtain ⟨q, hvq, hqEdge⟩ :=
    exists_otherEndpoint e₂ (mem_incidentEdges.mp he₂).2
  have hpq : p ≠ q := by
    intro hpq
    subst q
    apply he₁₂
    calc
      e₁ = simpleEdge v p hvp := hpEdge
      _ = simpleEdge v p hvq := by rfl
      _ = e₂ := hqEdge.symm
  refine ⟨{
    p := p, q := q, hvp := hvp, hvq := hvq, hpq := hpq,
    vp_mem := ?_, vq_mem := ?_ }⟩
  · rw [← hpEdge]
    exact (mem_incidentEdges.mp he₁).1
  · rw [← hqEdge]
    exact (mem_incidentEdges.mp he₂).1

omit [Fintype V] in
/-- Forgetting the third neighbour retains a genuine two-neighbour packet. -/
def DegreeThreeNeighbours.toTwo
    {F : SimpleEdgeSet V} {v : V} (N : DegreeThreeNeighbours F v) :
    TwoNeighbours F v where
  p := N.p
  q := N.q
  hvp := N.hvp
  hvq := N.hvq
  hpq := N.hpq
  vp_mem := N.vp_mem
  vq_mem := N.vq_mem

/-! ## Rank one and rank two force affine parameterizations -/

omit [Fintype V] [DecidableEq V] in
/-- With two distinct first points, the provenance collinearity predicate is
equivalent to the third displacement being a scalar multiple of the first
displacement. -/
theorem collinear_iff_exists_smul_difference
    (p q r : Fin 3 → K) (hpq : p ≠ q) :
    PinCollinearity.Collinear p q r ↔
      ∃ t : K, r - p = t • (q - p) := by
  constructor
  · rintro ⟨d, c₁, c₂, h₁, h₂⟩
    have hDiff : q - p ≠ 0 := sub_ne_zero.mpr (Ne.symm hpq)
    have hc₁ : c₁ ≠ 0 := by
      intro hc₁
      apply hDiff
      simpa [hc₁] using h₁
    refine ⟨c₂ * c₁⁻¹, ?_⟩
    rw [h₂, h₁, smul_smul]
    rw [mul_assoc, inv_mul_cancel₀ hc₁, mul_one]
  · rintro ⟨t, ht⟩
    exact ⟨q - p, 1, t, by simp, ht⟩

omit [Fintype V] [DecidableEq V] in
/-- If two apex differences lie in a vector space of dimension at most one,
then the apex lies on the affine line through their two distinct retained
endpoints. -/
theorem exists_line_parameter_of_finrank_le_one
    (point p q : Fin 3 → K) (S : Submodule K (Fin 3 → K))
    (hPointP : point ≠ p) (hPQ : p ≠ q)
    (hPointPMem : point - p ∈ S) (hPointQMem : point - q ∈ S)
    (hRank : Module.finrank K S ≤ 1) :
    ∃ t : K, point = p + t • (q - p) := by
  have hPointPDiff : point - p ≠ 0 := sub_ne_zero.mpr hPointP
  have hSpanLe : K ∙ (point - p) ≤ S :=
    (Submodule.span_singleton_le_iff_mem _ _).2 hPointPMem
  have hSpanRank : Module.finrank K (K ∙ (point - p)) = 1 :=
    finrank_span_singleton hPointPDiff
  have hSRank : Module.finrank K S = 1 := by
    have hMono := Submodule.finrank_mono hSpanLe
    rw [hSpanRank] at hMono
    omega
  have hSpanEq : K ∙ (point - p) = S := by
    exact Submodule.eq_of_le_of_finrank_eq hSpanLe (by
      rw [hSpanRank, hSRank])
  have hPointQSpan : point - q ∈ K ∙ (point - p) := by
    rw [hSpanEq]
    exact hPointQMem
  obtain ⟨c, hc⟩ := Submodule.mem_span_singleton.mp hPointQSpan
  have hOneSub : 1 - c ≠ 0 := by
    intro hzero
    have hcOne : c = 1 := (sub_eq_zero.mp hzero).symm
    apply hPQ
    have hSame : point - p = point - q := by simpa [hcOne] using hc
    funext j
    have hj := congrFun hSame j
    simp only [Pi.sub_apply] at hj
    exact sub_right_inj.mp hj
  have hDifference : q - p = (1 - c) • (point - p) := by
    calc
      q - p = (point - p) - (point - q) := by module
      _ = (point - p) - c • (point - p) := by rw [← hc]
      _ = (1 - c) • (point - p) := by module
  refine ⟨(1 - c)⁻¹, ?_⟩
  have hRecover : (1 - c)⁻¹ • (q - p) = point - p := by
    rw [hDifference, smul_smul]
    simp [hOneSub]
  rw [hRecover]
  module

omit [Fintype V] [DecidableEq V] in
/-- Noncollinearity of three points is linear independence of the two
displacements from the first point. -/
theorem linearIndependent_pair_differences_of_not_collinear
    (p q r : Fin 3 → K)
    (hNotCollinear : ¬ PinCollinearity.Collinear p q r) :
    LinearIndependent K ![q - p, r - p] := by
  have hPQ : p ≠ q := by
    intro hpq
    subst q
    apply hNotCollinear
    exact ⟨r - p, 0, 1, by simp, by simp⟩
  rw [LinearIndependent.pair_iff' (sub_ne_zero.mpr (Ne.symm hPQ))]
  intro c hc
  apply hNotCollinear
  apply (collinear_iff_exists_smul_difference p q r hPQ).2
  exact ⟨c, hc.symm⟩

omit [Fintype V] [DecidableEq V] in
/-- If three apex differences lie in a vector space of dimension at most
two and the retained endpoints are noncollinear, the apex lies in their
affine plane. -/
theorem exists_plane_parameters_of_finrank_le_two
    (point p q r : Fin 3 → K) (S : Submodule K (Fin 3 → K))
    (hPointPMem : point - p ∈ S)
    (hPointQMem : point - q ∈ S)
    (hPointRMem : point - r ∈ S)
    (hRank : Module.finrank K S ≤ 2)
    (hNotCollinear : ¬ PinCollinearity.Collinear p q r) :
    ∃ s t : K,
      point = p + s • (q - p) + t • (r - p) := by
  let pair : Fin 2 → (Fin 3 → K) := ![q - p, r - p]
  let T : Submodule K (Fin 3 → K) :=
    Submodule.span K (Set.range pair)
  have hLI : LinearIndependent K pair := by
    exact linearIndependent_pair_differences_of_not_collinear
      p q r hNotCollinear
  have hTRank : Module.finrank K T = 2 := by
    change Module.finrank K (Submodule.span K (Set.range pair)) = 2
    rw [finrank_span_eq_card hLI]
    simp
  have hQP : q - p ∈ S := by
    have := S.sub_mem hPointPMem hPointQMem
    convert this using 1
    module
  have hRP : r - p ∈ S := by
    have := S.sub_mem hPointPMem hPointRMem
    convert this using 1
    module
  have hTLe : T ≤ S := by
    change Submodule.span K (Set.range pair) ≤ S
    rw [Submodule.span_le]
    rintro _ ⟨i, rfl⟩
    fin_cases i
    · exact hQP
    · exact hRP
  have hSRank : Module.finrank K S = 2 := by
    have hMono := Submodule.finrank_mono hTLe
    rw [hTRank] at hMono
    omega
  have hTEq : T = S := by
    exact Submodule.eq_of_le_of_finrank_eq hTLe (by rw [hTRank, hSRank])
  have hPointPInT : point - p ∈ T := by
    rw [hTEq]
    exact hPointPMem
  obtain ⟨coefficient : Fin 2 → K, hCoefficient⟩ :=
    (Submodule.mem_span_range_iff_exists_fun K).mp hPointPInT
  refine ⟨coefficient 0, coefficient 1, ?_⟩
  have hExpanded : point - p =
      coefficient 0 • (q - p) + coefficient 1 • (r - p) := by
    simpa [pair, Fin.sum_univ_two] using hCoefficient.symm
  funext j
  have hj := congrFun hExpanded j
  simp only [Pi.sub_apply, Pi.add_apply, Pi.smul_apply, smul_eq_mul] at hj ⊢
  linear_combination hj

/-! ## Applying the affine parameterizations to the actual local map -/

omit [Fintype V] in
/-- Rank one for an actual degree-two-or-three outside star forces the
deleted point into a one-parameter retained affine line. -/
theorem outsideExtensionTrdeg_le_one_of_localRank_eq_one
    (F : SimpleEdgeSet V) (a : V → Fin 3 → K) (v : V)
    (ha : Function.Injective a)
    (hDegreeLower : 2 ≤ edgeSetDegree F v)
    (hDegreeUpper : edgeSetDegree F v ≤ 3)
    (hRank : outsideLocalRank F a v = 1)
    (hgen : IntermediateField.adjoin k
      (Set.range (fun c : V × Fin 3 ↦ a c.1 c.2)) = ⊤) :
    outsideExtensionTrdeg (k := k) a v ≤ 1 := by
  have hDegreeCases : edgeSetDegree F v = 2 ∨ edgeSetDegree F v = 3 := by
    omega
  have hTwoNeighbours : Nonempty (TwoNeighbours F v) := by
    rcases hDegreeCases with hTwo | hThree
    · exact exists_degreeTwoNeighbours F v hTwo
    · exact ⟨(Classical.choice
        (exists_degreeThreeNeighbours F v hThree)).toTwo⟩
  let N : TwoNeighbours F v := Classical.choice hTwoNeighbours
  have hPointP : a v ≠ a N.p := by
    intro h
    exact N.hvp (ha h)
  have hPQ : a N.p ≠ a N.q := by
    intro h
    exact N.hpq (ha h)
  have hPointPMem :
      a v - a N.p ∈ LinearMap.range (localEquilibriumAt F a v) :=
    namedNeighbourDifference_mem_localRange F a v N.p N.hvp N.vp_mem
  have hPointQMem :
      a v - a N.q ∈ LinearMap.range (localEquilibriumAt F a v) :=
    namedNeighbourDifference_mem_localRange F a v N.q N.hvq N.vq_mem
  have hline : ∃ t : K,
      a v = a N.p + t • (a N.q - a N.p) := by
    apply exists_line_parameter_of_finrank_le_one
      (a v) (a N.p) (a N.q)
      (LinearMap.range (localEquilibriumAt F a v))
      hPointP hPQ hPointPMem hPointQMem
    change outsideLocalRank F a v ≤ 1
    omega
  exact outsideExtensionTrdeg_le_one_of_line_parameter
    (k := k) a v N.p N.q N.hvp.symm N.hvq.symm hgen hline

omit [Fintype V] in
/-- Rank at most two together with three noncollinear actual neighbours
forces the deleted point into their two-parameter retained affine plane. -/
theorem outsideExtensionTrdeg_le_two_of_localRank_of_not_collinear
    (F : SimpleEdgeSet V) (a : V → Fin 3 → K) (v : V)
    (N : DegreeThreeNeighbours F v)
    (hRank : outsideLocalRank F a v ≤ 2)
    (hNotCollinear :
      ¬ PinCollinearity.Collinear (a N.p) (a N.q) (a N.r))
    (hgen : IntermediateField.adjoin k
      (Set.range (fun c : V × Fin 3 ↦ a c.1 c.2)) = ⊤) :
    outsideExtensionTrdeg (k := k) a v ≤ 2 := by
  have hPointPMem :
      a v - a N.p ∈ LinearMap.range (localEquilibriumAt F a v) :=
    namedNeighbourDifference_mem_localRange F a v N.p N.hvp N.vp_mem
  have hPointQMem :
      a v - a N.q ∈ LinearMap.range (localEquilibriumAt F a v) :=
    namedNeighbourDifference_mem_localRange F a v N.q N.hvq N.vq_mem
  have hPointRMem :
      a v - a N.r ∈ LinearMap.range (localEquilibriumAt F a v) :=
    namedNeighbourDifference_mem_localRange F a v N.r N.hvr N.vr_mem
  have hplane : ∃ s t : K,
      a v = a N.p + s • (a N.q - a N.p) +
        t • (a N.r - a N.p) := by
    apply exists_plane_parameters_of_finrank_le_two
      (a v) (a N.p) (a N.q) (a N.r)
      (LinearMap.range (localEquilibriumAt F a v))
      hPointPMem hPointQMem hPointRMem
    · simpa [outsideLocalRank] using hRank
    · exact hNotCollinear
  exact outsideExtensionTrdeg_le_two_of_plane_parameters
    (k := k) a v N.p N.q N.r
    N.hvp.symm N.hvq.symm N.hvr.symm hgen hplane

/-- **Outside-local classification.**  If a degree-at-most-three deletion
fails the three-coordinate payment at an injective, coordinate-generating
function-field point, then every part of the unique bad shape is forced by
the actual maps and fields:

* the degree is three;
* the three retained neighbours are pairwise distinct and collinear;
* the extension transcendence degree is exactly three;
* both `ker C_v` and the connecting kernel have dimension one;
* consequently the entire one-dimensional local relation space descends
  through the child row-space quotient.
-/
theorem outsideExceptional_classification
    (F : SimpleEdgeSet V) (a : V → Fin 3 → K) (v : V)
    (ha : Function.Injective a)
    (hDegree : edgeSetDegree F v ≤ 3)
    (hgen : IntermediateField.adjoin k
      (Set.range (fun c : V × Fin 3 ↦ a c.1 c.2)) = ⊤)
    (hExceptional : OutsideExceptional (k := k) F a v) :
    ∃ N : DegreeThreeNeighbours F v,
      PinCollinearity.Collinear (a N.p) (a N.q) (a N.r) ∧
      a N.p ≠ a N.q ∧ a N.p ≠ a N.r ∧ a N.q ≠ a N.r ∧
      outsideExtensionTrdeg (k := k) a v = 3 ∧
      outsideResponseKernelDim F a v = 1 ∧
      outsideLocalKernelDim F a v = 1 ∧
      outsideLocalRank F a v = 2 ∧
      deletedConnectingClass F a v = 0 := by
  let d : ℕ := (outsideExtensionTrdeg (k := k) a v).toNat
  have hTrdegCard := outsideExtensionTrdeg_le_three (k := k) a v hgen
  have hd : d ≤ 3 := by
    simpa [d] using Cardinal.toNat_le_toNat hTrdegCard
  have hFailure : 3 < outsideResponseKernelDim F a v + d := by
    unfold OutsideExceptional OutsideNonexceptional at hExceptional
    simpa [d] using (show
      3 < outsideResponseKernelDim F a v +
        (outsideExtensionTrdeg (k := k) a v).toNat by omega)
  have hResponseLe :=
    outsideResponseKernelDim_le_outsideLocalKernelDim F a v
  have hRankNullity := outsideLocalRank_add_kernelDim_eq_degree F a v
  have hResponsePos : 0 < outsideResponseKernelDim F a v := by omega
  have hDegreePos : 0 < edgeSetDegree F v := by omega
  have hRankPos :=
    outsideLocalRank_pos_of_injective_of_degree_pos F a v ha hDegreePos
  have hRankTwo : 2 ≤ outsideLocalRank F a v := by
    by_contra hNotTwo
    have hRankOne : outsideLocalRank F a v = 1 := by omega
    have hDegreeLower : 2 ≤ edgeSetDegree F v := by omega
    have hTrdegLeOne :=
      outsideExtensionTrdeg_le_one_of_localRank_eq_one
        (k := k) F a v ha hDegreeLower hDegree hRankOne hgen
    have hdOne : d ≤ 1 := by
      simpa [d] using Cardinal.toNat_le_toNat hTrdegLeOne
    omega
  obtain ⟨hdThree, hResponseOne, hKernelOne, hRankEqTwo,
      hDegreeThree⟩ :=
    outsidePaymentFailure_of_two_le_localRank F a v hDegree d hd
      hRankTwo hFailure
  let N : DegreeThreeNeighbours F v :=
    Classical.choice (exists_degreeThreeNeighbours F v hDegreeThree)
  have hCollinear :
      PinCollinearity.Collinear (a N.p) (a N.q) (a N.r) := by
    by_contra hNotCollinear
    have hTrdegLeTwo :=
      outsideExtensionTrdeg_le_two_of_localRank_of_not_collinear
        (k := k) F a v N (by omega) hNotCollinear hgen
    have hdTwo : d ≤ 2 := by
      simpa [d] using Cardinal.toNat_le_toNat hTrdegLeTwo
    omega
  have hTrdegFinite := outsideExtensionTrdeg_lt_aleph0 (k := k) a v hgen
  have hTrdegThree : outsideExtensionTrdeg (k := k) a v = 3 := by
    calc
      outsideExtensionTrdeg (k := k) a v =
          ((outsideExtensionTrdeg (k := k) a v).toNat : Cardinal) :=
        (Cardinal.cast_toNat_of_lt_aleph0 hTrdegFinite).symm
      _ = 3 := by
        change (d : Cardinal) = 3
        exact_mod_cast hdThree
  have hConnectingZero : deletedConnectingClass F a v = 0 := by
    apply LinearMap.ker_eq_top.mp
    apply Submodule.eq_of_le_of_finrank_eq le_top
    rw [finrank_top]
    change outsideResponseKernelDim F a v = outsideLocalKernelDim F a v
    rw [hResponseOne, hKernelOne]
  refine ⟨N, hCollinear, ?_, ?_, ?_, hTrdegThree,
    hResponseOne, hKernelOne, hRankEqTwo, hConnectingZero⟩
  · exact fun h ↦ N.hpq (ha h)
  · exact fun h ↦ N.hpr (ha h)
  · exact fun h ↦ N.hqr (ha h)

end

end DirectionStress

end RB31E2E
