import RB31EndToEnd.Linear.PrivateLocalClassification

/-!
# Direction-stress invariance under a private flag pivot

On three distinct collinear placed points, every triangle direction row is
in the span of the other two.  Consequently exchanging one live terminal
edge for the distinguished missing terminal edge preserves both the
literal row space and the stress dimension.
-/

namespace RB31E2E

namespace DirectionStress

noncomputable section

universe u w

variable {K : Type u} {V : Type w}
  [Field K] [Fintype V] [DecidableEq V]

omit [Fintype V] in
private theorem directionRow_mem_rowSpace_of_mem
    (F : SimpleEdgeSet V) (pos : V → Fin 3 → K)
    (e : SimpleEdge V) (he : e ∈ F) :
    directionRow pos e ∈ directionRowSpace F pos := by
  apply Submodule.subset_span
  exact ⟨⟨e, he⟩, rfl⟩

omit [Fintype V] in
/-- For three distinct collinear points, the edge between the second and
third points is a virtual response row generated by the two star edges at
the first point. -/
theorem triangleThirdRow_mem_of_collinear
    (F : SimpleEdgeSet V) (pos : V → Fin 3 → K) (x y z : V)
    (hxy : x ≠ y) (hxz : x ≠ z) (hyz : y ≠ z)
    (hxyMem : simpleEdge x y hxy ∈ F)
    (hxzMem : simpleEdge x z hxz ∈ F)
    (hpos : Function.Injective pos)
    (hcol : PinCollinearity.Collinear (pos x) (pos y) (pos z)) :
    directionRow pos (simpleEdge y z hyz) ∈ directionRowSpace F pos := by
  have hxyPos : pos x ≠ pos y := fun h ↦ hxy (hpos h)
  obtain ⟨t, hline⟩ :=
    (collinear_iff_exists_smul_difference
      (pos x) (pos y) (pos z) hxyPos).1 hcol
  have ht : t ≠ 0 := by
    intro htZero
    apply hxz
    apply hpos
    exact (sub_eq_zero.mp (by simpa [htZero] using hline)).symm
  have hxyRow := directionRow_mem_rowSpace_of_mem
    F pos (simpleEdge x y hxy) hxyMem
  have hxzRow := directionRow_mem_rowSpace_of_mem
    F pos (simpleEdge x z hxz) hxzMem
  have hScaled :
      t • directionRow pos (simpleEdge y z hyz) ∈
        directionRowSpace F pos := by
    rw [triangleRows_scaled_identity pos x y z hxy hxz hyz t hline]
    exact (directionRowSpace F pos).add_mem
      ((directionRowSpace F pos).smul_mem _ hxyRow)
      ((directionRowSpace F pos).smul_mem _ hxzRow)
  have hCancel := (directionRowSpace F pos).smul_mem t⁻¹ hScaled
  have htCancel : t⁻¹ * t = 1 := inv_mul_cancel₀ ht
  simpa only [smul_smul, htCancel, one_smul] using hCancel

omit [Fintype V] in
/-- The second star edge is likewise generated by the first star edge and
the opposite triangle edge. -/
theorem triangleSecondRow_mem_of_collinear
    (F : SimpleEdgeSet V) (pos : V → Fin 3 → K) (x y z : V)
    (hxy : x ≠ y) (hxz : x ≠ z) (hyz : y ≠ z)
    (hxyMem : simpleEdge x y hxy ∈ F)
    (hyzMem : simpleEdge y z hyz ∈ F)
    (hpos : Function.Injective pos)
    (hcol : PinCollinearity.Collinear (pos x) (pos y) (pos z)) :
    directionRow pos (simpleEdge x z hxz) ∈ directionRowSpace F pos := by
  have hxyPos : pos x ≠ pos y := fun h ↦ hxy (hpos h)
  obtain ⟨t, hline⟩ :=
    (collinear_iff_exists_smul_difference
      (pos x) (pos y) (pos z) hxyPos).1 hcol
  have htOne : t - 1 ≠ 0 := by
    intro ht
    have htEq : t = 1 := sub_eq_zero.mp ht
    apply hyz
    apply hpos
    have hzero : pos z - pos y = 0 := by
      funext j
      have hj := congrFun hline j
      simp only [Pi.sub_apply, Pi.smul_apply, smul_eq_mul,
        Pi.zero_apply] at hj ⊢
      rw [htEq] at hj
      linear_combination hj
    exact (sub_eq_zero.mp hzero).symm
  have hxyRow := directionRow_mem_rowSpace_of_mem
    F pos (simpleEdge x y hxy) hxyMem
  have hyzRow := directionRow_mem_rowSpace_of_mem
    F pos (simpleEdge y z hyz) hyzMem
  have hIdentity :=
    triangleRows_scaled_identity pos x y z hxy hxz hyz t hline
  have hScaled :
      (t - 1) • directionRow pos (simpleEdge x z hxz) ∈
        directionRowSpace F pos := by
    have hEq :
        (t - 1) • directionRow pos (simpleEdge x z hxz) =
          t • directionRow pos (simpleEdge y z hyz) -
            (t * (1 - t)) • directionRow pos (simpleEdge x y hxy) := by
      rw [hIdentity]
      module
    rw [hEq]
    exact (directionRowSpace F pos).sub_mem
      ((directionRowSpace F pos).smul_mem _ hyzRow)
      ((directionRowSpace F pos).smul_mem _ hxyRow)
  have hCancel := (directionRowSpace F pos).smul_mem (t - 1)⁻¹ hScaled
  have htCancel : (t - 1)⁻¹ * (t - 1) = 1 := inv_mul_cancel₀ htOne
  simpa only [smul_smul, htCancel, one_smul] using hCancel

omit [Fintype V] in
/-- Exchanging one labelled row for a genuinely new labelled row preserves
the row space when each exchanged row lies in the other system's span. -/
theorem directionRowSpace_exchange_eq
    (F : SimpleEdgeSet V) (pos : V → Fin 3 → K)
    (remove add : SimpleEdge V)
    (_hRemove : remove ∈ F) (_hAdd : add ∉ F)
    (hAddRow : directionRow pos add ∈ directionRowSpace F pos)
    (hRemoveRow : directionRow pos remove ∈
      directionRowSpace (insert add (F.erase remove)) pos) :
    directionRowSpace (insert add (F.erase remove)) pos =
      directionRowSpace F pos := by
  apply le_antisymm
  · rw [directionRowSpace, Submodule.span_le]
    rintro _ ⟨e, rfl⟩
    by_cases hea : e.1 = add
    · simpa only [hea] using hAddRow
    · apply Submodule.subset_span
      have heErase : e.1 ∈ F.erase remove :=
        (Finset.mem_insert.mp e.2).resolve_left hea
      exact ⟨⟨e.1, Finset.mem_erase.mp heErase |>.2⟩, rfl⟩
  · rw [directionRowSpace, Submodule.span_le]
    rintro _ ⟨e, rfl⟩
    by_cases her : e.1 = remove
    · simpa only [her] using hRemoveRow
    · apply Submodule.subset_span
      exact ⟨⟨e.1, Finset.mem_insert_of_mem
        (Finset.mem_erase.mpr ⟨her, e.2⟩)⟩, rfl⟩

/-- Stress dimension is invariant under a collinear terminal-edge pivot. -/
theorem directionStressDim_exchange_collinear_triangle
    (F : SimpleEdgeSet V) (pos : V → Fin 3 → K) (x y z : V)
    (hxy : x ≠ y) (hxz : x ≠ z) (hyz : y ≠ z)
    (hxyMem : simpleEdge x y hxy ∈ F)
    (hxzMem : simpleEdge x z hxz ∈ F)
    (hyzNotMem : simpleEdge y z hyz ∉ F)
    (hpos : Function.Injective pos)
    (hcol : PinCollinearity.Collinear (pos x) (pos y) (pos z)) :
    directionStressDim
        (insert (simpleEdge y z hyz) (F.erase (simpleEdge x z hxz))) pos =
      directionStressDim F pos := by
  let F' := insert (simpleEdge y z hyz) (F.erase (simpleEdge x z hxz))
  have hxyF' : simpleEdge x y hxy ∈ F' := by
    apply Finset.mem_insert_of_mem
    exact Finset.mem_erase.mpr
      ⟨by
        intro hEq
        rw [simpleEdge_eq_simpleEdge_iff] at hEq
        rcases hEq with h | h
        · exact hyz h.2
        · exact hxz h.1,
       hxyMem⟩
  have hyzF' : simpleEdge y z hyz ∈ F' := Finset.mem_insert_self _ _
  have hAddRow : directionRow pos (simpleEdge y z hyz) ∈
      directionRowSpace F pos :=
    triangleThirdRow_mem_of_collinear F pos x y z hxy hxz hyz
      hxyMem hxzMem hpos hcol
  have hRemoveRow : directionRow pos (simpleEdge x z hxz) ∈
      directionRowSpace F' pos :=
    triangleSecondRow_mem_of_collinear F' pos x y z hxy hxz hyz
      hxyF' hyzF' hpos hcol
  have hRows : directionRowSpace F' pos = directionRowSpace F pos :=
    directionRowSpace_exchange_eq F pos
      (simpleEdge x z hxz) (simpleEdge y z hyz)
      hxzMem hyzNotMem hAddRow hRemoveRow
  have hRank : directionEquilibriumRank F' pos =
      directionEquilibriumRank F pos := by
    rw [directionEquilibriumRank_eq_finrank_rowSpace,
      directionEquilibriumRank_eq_finrank_rowSpace, hRows]
  have hAddNotErase : simpleEdge y z hyz ∉
      F.erase (simpleEdge x z hxz) := by
    exact fun h ↦ hyzNotMem (Finset.mem_erase.mp h).2
  have hCard : F'.card = F.card := by
    dsimp [F']
    rw [Finset.card_insert_of_notMem hAddNotErase,
      Finset.card_erase_of_mem hxzMem]
    have hCardPos : 0 < F.card :=
      Finset.card_pos.mpr ⟨simpleEdge x z hxz, hxzMem⟩
    omega
  have hPivot := directionStressDim_add_directionEquilibriumRank F' pos
  have hOriginal := directionStressDim_add_directionEquilibriumRank F pos
  rw [hRank, hCard] at hPivot
  exact Nat.add_right_cancel (hPivot.trans hOriginal.symm)

end

end DirectionStress

end RB31E2E
