import RB31EndToEnd.Algebra.MinimalPrimeLinearFibreHeight
import RB31EndToEnd.Algebra.LinearFormIdealHeight

/-!
# Generic fibre of a coefficient-linear row ideal

A family of polynomials linear in the outer variables remains the literal
linear row ideal after quotienting and localizing its coefficient ring.  A
minimal prime above it therefore has precisely that generic fibre.
-/

namespace RB31E2E

namespace CoefficientLinearFibre

noncomputable section

open MvPolynomial
open PolynomialPrimeTrdegHeight
open MinimalPrimeLinearFibre

attribute [local instance] MvPolynomial.algebraMvPolynomial

/-- A homogeneous linear polynomial over an arbitrary commutative
coefficient ring. -/
def linearPolynomialOver
    {A τ : Type*} [CommRing A] [Fintype τ]
    (v : τ → A) : MvPolynomial τ A :=
  ∑ i, C (v i) * X i

/-- The ideal generated by a coefficient-valued row family. -/
def linearFormIdealOver
    {A τ J : Type*} [CommRing A] [Fintype τ]
    (row : J → τ → A) : Ideal (MvPolynomial τ A) :=
  Ideal.span (Set.range (fun j ↦ linearPolynomialOver (row j)))

theorem map_linearPolynomialOver
    {A B τ : Type*} [CommRing A] [CommRing B] [Fintype τ]
    (f : A →+* B) (v : τ → A) :
    MvPolynomial.map f (linearPolynomialOver v) =
      linearPolynomialOver (fun i ↦ f (v i)) := by
  simp [linearPolynomialOver]

theorem map_linearFormIdealOver
    {A B τ J : Type*} [CommRing A] [CommRing B] [Fintype τ]
    (f : A →+* B) (row : J → τ → A) :
    Ideal.map (MvPolynomial.map f) (linearFormIdealOver row) =
      linearFormIdealOver (fun j i ↦ f (row j i)) := by
  rw [linearFormIdealOver, linearFormIdealOver, Ideal.map_span]
  congr 1
  ext g
  constructor
  · rintro ⟨p, ⟨j, rfl⟩, rfl⟩
    exact ⟨j, (map_linearPolynomialOver f (row j)).symm⟩
  · rintro ⟨j, rfl⟩
    refine ⟨linearPolynomialOver (row j), ⟨j, rfl⟩, ?_⟩
    exact map_linearPolynomialOver f (row j)

theorem linearPolynomialOver_eq_linearPolynomial
    {k τ : Type*} [Field k] [Fintype τ]
    (v : τ → k) :
    linearPolynomialOver v =
      LinearFormIdeal.linearPolynomial v := rfl

theorem linearFormIdealOver_eq_linearFormIdeal
    {k τ J : Type*} [Field k] [Fintype τ]
    (row : J → τ → k) :
    linearFormIdealOver row =
      LinearFormIdeal.linearFormIdeal row := rfl

/-- The generic fibre of a minimal prime above a coefficient-linear row
ideal is exactly the ordinary linear-form ideal obtained by mapping the
row coefficients to the coefficient fraction field. -/
theorem fractionFibrePrime_eq_linearFormIdeal
    {A τ J : Type*} [CommRing A]
    [Fintype τ] [DecidableEq τ]
    (row : J → τ → A)
    (P : Ideal (MvPolynomial τ A)) [P.IsPrime]
    [(coefficientContraction P).IsPrime]
    (hP : P ∈ (linearFormIdealOver row).minimalPrimes) :
    let p := coefficientContraction P
    let B := A ⧸ p
    let K := FractionRing B
    let q := coefficientQuotientMap (τ := τ) p
    let ℓ := MvPolynomial.map (algebraMap B K)
    let rowK : J → τ → K := fun j i ↦
      algebraMap B K (Ideal.Quotient.mk p (row j i))
    Ideal.map ℓ (Ideal.map q P) =
      LinearFormIdeal.linearFormIdeal rowK := by
  classical
  dsimp only
  let p := coefficientContraction P
  let B := A ⧸ p
  let K := FractionRing B
  let q := coefficientQuotientMap (τ := τ) p
  let ℓ : MvPolynomial τ B →+* MvPolynomial τ K :=
    MvPolynomial.map (algebraMap B K)
  let rowK : J → τ → K := fun j i ↦
    algebraMap B K (Ideal.Quotient.mk p (row j i))
  have hmapq : Ideal.map q (linearFormIdealOver row) =
      linearFormIdealOver (fun j i ↦ Ideal.Quotient.mk p (row j i)) := by
    exact map_linearFormIdealOver (Ideal.Quotient.mk p) row
  have hmapℓ : Ideal.map ℓ
      (linearFormIdealOver
        (fun j i ↦ Ideal.Quotient.mk p (row j i))) =
      LinearFormIdeal.linearFormIdeal rowK := by
    rw [map_linearFormIdealOver]
    rfl
  have hIeq : Ideal.map ℓ
      (Ideal.map q (linearFormIdealOver row)) =
      LinearFormIdeal.linearFormIdeal rowK := by
    rw [hmapq, hmapℓ]
  have hI : Ideal.map ℓ
      (Ideal.map q (linearFormIdealOver row)) ≤
      LinearFormIdeal.linearFormIdeal rowK := hIeq.le
  have hPupper : LinearFormIdeal.linearFormIdeal rowK ≤
      Ideal.map ℓ (Ideal.map q P) := by
    rw [← hIeq]
    exact Ideal.map_mono (Ideal.map_mono hP.1.2)
  exact (linearFormIdeal_eq_fractionFibrePrime
    (linearFormIdealOver row) P hP rowK hI hPupper).symm

end

end CoefficientLinearFibre

end RB31E2E
