import RB31EndToEnd.Algebra.FiniteCoordinateTrdeg

/-!
# Splitting a finite coordinate-generated function field

Deleting a live vertex separates the generic coordinate functions into an
old family and a finite new family.  This file constructs the intermediate
field generated by the old coordinates and proves both parts of the exact
transcendence-degree ledger:

* the total field is generated over the old-coordinate field by the new
  coordinate family;
* the tower transcendence degrees add, and the extension degree is bounded
  by the number of new coordinate labels.

No geometric fibre-dimension theorem is used or assumed.
-/

namespace RB31E2E

namespace CoordinateFieldTower

noncomputable section

open scoped IntermediateField.algebraAdjoinAdjoin

universe u v w x

variable {k : Type u} {K : Type v} {Old : Type w} {New : Type x}
  [Field k] [Field K] [Algebra k K]

/-- The intermediate field generated by the old coordinate family. -/
abbrev oldCoordinateField (old : Old → K) : IntermediateField k K :=
  IntermediateField.adjoin k (Set.range old)

/-- If old and new coordinate families together generate `K`, then the new
family generates `K` over the intermediate field generated by the old
family. -/
theorem adjoin_new_over_old_eq_top
    (old : Old → K) (new : New → K)
    (hgen : IntermediateField.adjoin k
      (Set.range old ∪ Set.range new) = ⊤) :
    IntermediateField.adjoin
      (oldCoordinateField (k := k) (K := K) old) (Set.range new) = ⊤ := by
  apply (IntermediateField.restrictScalars_eq_top_iff (K := k)).mp
  rw [IntermediateField.adjoin_adjoin_left]
  exact hgen

/-- The extension from the old-coordinate field to the full field has
transcendence degree at most the cardinality of the new labels. -/
theorem extension_trdeg_le_card
    [Fintype New]
    (old : Old → K) (new : New → K)
    (hgen : IntermediateField.adjoin k
      (Set.range old ∪ Set.range new) = ⊤) :
    Algebra.trdeg (oldCoordinateField (k := k) (K := K) old) K ≤
      (Fintype.card New : Cardinal) := by
  exact FiniteCoordinateTrdeg.trdeg_le_card_of_adjoin_range_eq_top
    (k := oldCoordinateField (k := k) (K := K) old) (K := K)
    new (adjoin_new_over_old_eq_top (k := k) old new hgen)

/-- Exact transcendence-degree tower for the old-coordinate intermediate
field. -/
theorem trdeg_old_add_extension
    (old : Old → K) :
    Algebra.trdeg k (oldCoordinateField (k := k) (K := K) old) +
        Algebra.trdeg (oldCoordinateField (k := k) (K := K) old) K =
      Algebra.trdeg k K := by
  exact trdeg_add_eq k
    (oldCoordinateField (k := k) (K := K) old)

/-- Packaged deletion ledger: the tower equality and the finite extension
bound are both derived from the literal coordinate-generation equation. -/
theorem trdeg_deletion_ledger
    [Fintype New]
    (old : Old → K) (new : New → K)
    (hgen : IntermediateField.adjoin k
      (Set.range old ∪ Set.range new) = ⊤) :
    Algebra.trdeg k (oldCoordinateField (k := k) (K := K) old) +
          Algebra.trdeg (oldCoordinateField (k := k) (K := K) old) K =
        Algebra.trdeg k K ∧
      Algebra.trdeg (oldCoordinateField (k := k) (K := K) old) K ≤
        (Fintype.card New : Cardinal) := by
  exact ⟨trdeg_old_add_extension (k := k) old,
    extension_trdeg_le_card (k := k) old new hgen⟩

end

end CoordinateFieldTower

end RB31E2E
