import Mathlib.RingTheory.AlgebraicIndependent.TranscendenceBasis
import Mathlib.RingTheory.AlgebraicIndependent.AlgebraicClosure

/-!
# Transcendence degree of a finitely generated function field

These lemmas turn the literal statement that a field is generated by a
finite labelled coordinate family into a cardinal bound on its
transcendence degree.  They are used by the function-field formulation of
provenance-flag semismallness.
-/

namespace RB31E2E

noncomputable section

namespace FiniteCoordinateTrdeg

open scoped IntermediateField.algebraAdjoinAdjoin

universe u v w

variable {k : Type u} {K : Type v} {ι : Type w}
  [Field k] [Field K] [Algebra k K]

/-- A field generated by the range of `x` has transcendence degree at most
the cardinality of the source labels. -/
theorem trdeg_le_cardinalMk_of_adjoin_range_eq_top
    (x : ι → K)
    (hgen : IntermediateField.adjoin k (Set.range x) = ⊤) :
    Cardinal.lift.{w} (Algebra.trdeg k K) ≤
      Cardinal.lift.{v} (Cardinal.mk ι) := by
  let L := IntermediateField.adjoin k (Set.range x)
  have hL : Algebra.IsAlgebraic L K := ⟨fun y ↦ by
    have hy : y ∈ L := by
      change y ∈ IntermediateField.adjoin k (Set.range x)
      rw [hgen]
      exact trivial
    have hmap : algebraMap L K (⟨y, hy⟩ : L) = y := rfl
    rw [← hmap]
    exact isAlgebraic_algebraMap _⟩
  have hA : Algebra.IsAlgebraic (Algebra.adjoin k (Set.range x)) K :=
    (IntermediateField.isAlgebraic_adjoin_iff_top (s := Set.range x)).mp hL
  letI : Algebra.IsAlgebraic (Algebra.adjoin k (Set.range x)) K := hA
  have hraw := Algebra.IsAlgebraic.trdeg_le_cardinalMk
    k (Set.range x)
  exact (Cardinal.lift_monotone hraw).trans Cardinal.mk_range_le_lift

/-- Finite-type version of the preceding bound. -/
theorem trdeg_le_card_of_adjoin_range_eq_top
    [Fintype ι] (x : ι → K)
    (hgen : IntermediateField.adjoin k (Set.range x) = ⊤) :
    Algebra.trdeg k K ≤ (Fintype.card ι : Cardinal) := by
  simpa using trdeg_le_cardinalMk_of_adjoin_range_eq_top x hgen

/-- If a finite coordinate family generates the whole field and its number
of labels is no larger than the transcendence degree, then the coordinates
are algebraically independent.  This coefficient comparison is used in the
exceptional local steps of provenance-flag induction. -/
theorem algebraicIndependent_of_card_le_trdeg_of_adjoin_range_eq_top
    [Fintype ι] (x : ι → K)
    (hgen : IntermediateField.adjoin k (Set.range x) = ⊤)
    (hle : (Fintype.card ι : Cardinal) ≤ Algebra.trdeg k K) :
    AlgebraicIndependent k x := by
  let L := IntermediateField.adjoin k (Set.range x)
  have hL : Algebra.IsAlgebraic L K := ⟨fun y ↦ by
    have hy : y ∈ L := by
      change y ∈ IntermediateField.adjoin k (Set.range x)
      rw [hgen]
      exact trivial
    have hmap : algebraMap L K (⟨y, hy⟩ : L) = y := rfl
    rw [← hmap]
    exact isAlgebraic_algebraMap _⟩
  have hA : Algebra.IsAlgebraic (Algebra.adjoin k (Set.range x)) K :=
    (IntermediateField.isAlgebraic_adjoin_iff_top (s := Set.range x)).mp hL
  letI : Algebra.IsAlgebraic (Algebra.adjoin k (Set.range x)) K := hA
  letI : FaithfulSMul k K :=
    (faithfulSMul_iff_algebraMap_injective k K).2 (RingHom.injective _)
  have hleLift :
      Cardinal.lift.{v} (Cardinal.mk ι) ≤
        Cardinal.lift.{w} (Algebra.trdeg k K) := by
    simpa using Cardinal.lift_monotone.{v, w} hle
  have htb : IsTranscendenceBasis k x :=
    Algebra.IsAlgebraic.isTranscendenceBasis_of_lift_le_trdeg_of_finite.{w, v, u}
      k x hleLift
  exact htb.1

/-- A field generated by `V × Fin 3` coordinate functions has dimension at
most `3 * |V|`. -/
theorem trdeg_le_three_mul_card
    {V : Type*} [Fintype V]
    (x : V × Fin 3 → K)
    (hgen : IntermediateField.adjoin k (Set.range x) = ⊤) :
    Algebra.trdeg k K ≤ 3 * (Fintype.card V : Cardinal) := by
  calc
    Algebra.trdeg k K ≤ (Fintype.card (V × Fin 3) : Cardinal) :=
      trdeg_le_card_of_adjoin_range_eq_top x hgen
    _ = 3 * (Fintype.card V : Cardinal) := by
      simp [mul_comm]

end FiniteCoordinateTrdeg

end

end RB31E2E
