import RB31EndToEnd.Algebra.FilteredInitialHeight
import Mathlib.RingTheory.GradedAlgebra.Homogeneous.Ideal
import Mathlib.RingTheory.MvPolynomial.Homogeneous

/-!
# Height loss on a homogeneous affine chart

Let `P` be a homogeneous prime in the standard-graded polynomial ring
`k[X₀, ..., Xₙ₋₁]`.  If one coordinate `X i` does not vanish modulo `P`,
then `P` is strictly below the irrelevant maximal ideal.  The latter has
height `n`, so `P` has height at most `n - 1`.

This is the algebraic end of the normalized-chart argument used by the
body--pin project.  The proof is elementary and keeps all provenance visible:

* homogeneity extracts the degree-zero component of every member of `P`;
* primality/properness over a field forces that constant component to vanish;
* hence `P` lies in the coordinate ideal generated by all variables;
* the omitted coordinate makes this inclusion strict;
* an explicit coordinate-prime chain and Krull's height theorem compute the
  height of that coordinate ideal.

The argument uses only homogeneity, primality, and an explicit coordinate
prime chain.
-/

namespace RB31E2E

namespace NullCellulePolynomial

noncomputable section

open MvPolynomial

attribute [local instance] MvPolynomial.gradedAlgebra

variable {k : Type*} [Field k]

/-- The standard irrelevant ideal in a finite-variable polynomial ring,
written using the coordinate-ideal implementation from
`FilteredInitialHeight`. -/
def finiteIrrelevantIdeal (n : ℕ) :
    Ideal (MvPolynomial (Fin n) k) :=
  coordinateVariableIdeal (k := k) (Set.univ : Set (Fin n))

/-- The finite-variable irrelevant ideal is prime.  Its quotient is the
coefficient field. -/
theorem finiteIrrelevantIdeal_isPrime (n : ℕ) :
    (finiteIrrelevantIdeal (k := k) n).IsPrime := by
  exact coordinateVariableIdeal_isPrime
    (k := k) (Set.univ : Set (Fin n))

/-- The height of the irrelevant ideal in `n` variables is exactly `n`.

The lower bound is the explicit chain obtained by adjoining the variables
one at a time.  The upper bound uses that the ideal is generated by the `n`
coordinate variables. -/
theorem finiteIrrelevantIdeal_height (n : ℕ) :
    (finiteIrrelevantIdeal (k := k) n).height = (n : ℕ∞) := by
  let c : Fin n → Fin n := fun i ↦ i
  have hc : Function.Injective c := Function.injective_id
  have hlower :
      (n : ℕ∞) ≤ (finiteIrrelevantIdeal (k := k) n).height := by
    simpa [finiteIrrelevantIdeal, c] using
      (coordinateVariableIdeal_height_ge_card (k := k) c hc)
  have hspan :
      (finiteIrrelevantIdeal (k := k) n).spanFinrank ≤ n := by
    let g : Fin n → MvPolynomial (Fin n) k := fun i ↦ X i
    rw [finiteIrrelevantIdeal, coordinateVariableIdeal, Set.image_univ]
    change (Ideal.span (Set.range g)).spanFinrank ≤ n
    refine (Submodule.spanFinrank_span_le_ncard_of_finite
      (Set.finite_range g)).trans ?_
    rw [← Set.image_univ]
    simpa using Set.ncard_image_le (f := g) (s := Set.univ)
  have hne : finiteIrrelevantIdeal (k := k) n ≠ ⊤ :=
    (finiteIrrelevantIdeal_isPrime (k := k) n).ne_top
  apply le_antisymm
  · apply (Ideal.height_le_spanFinrank _ hne).trans
    exact_mod_cast hspan
  · exact hlower

/-- A proper standard-homogeneous ideal over a field is contained in the
irrelevant ideal.  The field hypothesis is used exactly once: a nonzero
constant is a unit and therefore cannot belong to a proper ideal. -/
theorem homogeneousIdeal_le_finiteIrrelevantIdeal
    {n : ℕ} (P : Ideal (MvPolynomial (Fin n) k))
    (hPproper : P ≠ ⊤)
    (hPhom : P.IsHomogeneous
      (MvPolynomial.homogeneousSubmodule (Fin n) k)) :
    P ≤ finiteIrrelevantIdeal (k := k) n := by
  intro f hf
  have hcomponent : homogeneousComponent 0 f ∈ P := by
    rw [← MvPolynomial.decomposition.decompose'_apply f 0]
    exact hPhom 0 hf
  have hconstant : C (coeff 0 f) ∈ P := by
    simpa using hcomponent
  have hcoeff : coeff 0 f = 0 := by
    by_contra hne
    have hunit : IsUnit (C (coeff 0 f) : MvPolynomial (Fin n) k) :=
      (isUnit_iff_ne_zero.mpr hne).map C
    exact hPproper (P.eq_top_of_isUnit_mem hconstant hunit)
  rw [finiteIrrelevantIdeal, coordinateVariableIdeal,
    MvPolynomial.mem_ideal_span_X_image]
  intro m hm
  have hm0 : m ≠ 0 := by
    intro hzero
    subst m
    exact (MvPolynomial.mem_support_iff.mp hm) hcoeff
  rw [Finsupp.ne_iff] at hm0
  obtain ⟨j, hj⟩ := hm0
  exact ⟨j, Set.mem_univ j, hj⟩

/-- Strict height loss on a nonvanishing homogeneous coordinate chart.

This `< n` form is often the most convenient one for dimension arguments. -/
theorem homogeneousPrime_height_lt_of_X_not_mem
    {n : ℕ} (P : Ideal (MvPolynomial (Fin n) k)) [P.IsPrime]
    (hPhom : P.IsHomogeneous
      (MvPolynomial.homogeneousSubmodule (Fin n) k))
    (i : Fin n) (hi : X i ∉ P) :
    P.height < (n : ℕ∞) := by
  have hle : P ≤ finiteIrrelevantIdeal (k := k) n :=
    homogeneousIdeal_le_finiteIrrelevantIdeal P
      Ideal.IsPrime.ne_top' hPhom
  have hXi : X i ∈ finiteIrrelevantIdeal (k := k) n := by
    exact (X_mem_coordinateVariableIdeal_iff
      (k := k) (Set.univ : Set (Fin n)) i).2 (Set.mem_univ i)
  have hlt : P < finiteIrrelevantIdeal (k := k) n := by
    refine lt_of_le_of_ne hle ?_
    intro heq
    apply hi
    rw [heq]
    exact hXi
  rw [← finiteIrrelevantIdeal_height (k := k) n]
  exact Ideal.height_strict_mono_of_is_prime hlt

/-- A homogeneous prime missing one coordinate has height at most `n - 1`.
This is the exact affine-chart bound: normalizing a nonvanishing homogeneous
coordinate removes one dimension from the possible prime height. -/
theorem homogeneousPrime_height_le_pred_of_X_not_mem
    {n : ℕ} (P : Ideal (MvPolynomial (Fin n) k)) [P.IsPrime]
    (hPhom : P.IsHomogeneous
      (MvPolynomial.homogeneousSubmodule (Fin n) k))
    (i : Fin n) (hi : X i ∉ P) :
    P.height ≤ ((n - 1 : ℕ) : ℕ∞) := by
  have hlt := homogeneousPrime_height_lt_of_X_not_mem
    (k := k) P hPhom i hi
  have hn : 0 < n := Nat.zero_lt_of_lt i.isLt
  have hre : (n : ℕ∞) = ((n - 1 : ℕ) : ℕ∞) + 1 := by
    norm_cast
    omega
  rw [hre, ENat.lt_add_one_iff (ENat.coe_ne_top (n - 1))] at hlt
  exact hlt

/-- Equivalent irrelevant-ideal formulation: if a homogeneous prime has
height at least the number of ambient variables, then every coordinate
variable belongs to it. -/
theorem all_X_mem_homogeneousPrime_of_card_le_height
    {n : ℕ} (P : Ideal (MvPolynomial (Fin n) k)) [P.IsPrime]
    (hPhom : P.IsHomogeneous
      (MvPolynomial.homogeneousSubmodule (Fin n) k))
    (hheight : (n : ℕ∞) ≤ P.height) :
    ∀ i : Fin n, X i ∈ P := by
  intro i
  by_contra hi
  exact (not_lt_of_ge hheight)
    (homogeneousPrime_height_lt_of_X_not_mem
      (k := k) P hPhom i hi)

/-- A homogeneous prime of height at least `n` is the irrelevant maximal
ideal itself.  This packages both the height obstruction and its full
coordinate provenance. -/
theorem homogeneousPrime_eq_finiteIrrelevantIdeal_of_card_le_height
    {n : ℕ} (P : Ideal (MvPolynomial (Fin n) k)) [P.IsPrime]
    (hPhom : P.IsHomogeneous
      (MvPolynomial.homogeneousSubmodule (Fin n) k))
    (hheight : (n : ℕ∞) ≤ P.height) :
    P = finiteIrrelevantIdeal (k := k) n := by
  apply le_antisymm
  · exact homogeneousIdeal_le_finiteIrrelevantIdeal P
      Ideal.IsPrime.ne_top' hPhom
  · rw [finiteIrrelevantIdeal, coordinateVariableIdeal, Ideal.span_le]
    rintro _ ⟨i, -, rfl⟩
    exact all_X_mem_homogeneousPrime_of_card_le_height
      (k := k) P hPhom hheight i

end

end NullCellulePolynomial

end RB31E2E
