import RB31EndToEnd.Algebra.FilteredInitialHeight
import Mathlib.LinearAlgebra.StdBasis
import Mathlib.LinearAlgebra.Dimension.Free
import Mathlib.Algebra.MvPolynomial.Equiv

/-!
# Prime ideals generated by finite linear row systems

For a finite coordinate type, every ideal generated by homogeneous linear
forms over a field is prime.  The proof retains the actual row family:
it extends a basis of the row span to an ambient basis and constructs the
induced polynomial linear-change automorphism explicitly.  Under this
automorphism the row ideal is a coordinate-variable ideal.

No rank or primality statement is supplied as a premise.
-/

namespace RB31E2E

namespace LinearFormIdeal

noncomputable section

open MvPolynomial
open NullCellulePolynomial

variable {k I : Type*} [Field k] [Fintype I] [DecidableEq I]

/-- The homogeneous linear polynomial with coefficient vector `v`. -/
def linearPolynomial (v : I → k) : MvPolynomial I k :=
  ∑ i, C (v i) * X i

omit [DecidableEq I] in
@[simp] theorem linearPolynomial_zero :
    linearPolynomial (k := k) (I := I) 0 = 0 := by
  simp [linearPolynomial]

omit [DecidableEq I] in
theorem linearPolynomial_add (u v : I → k) :
    linearPolynomial (u + v) = linearPolynomial u + linearPolynomial v := by
  simp only [linearPolynomial, Pi.add_apply, map_add, add_mul,
    Finset.sum_add_distrib]

omit [DecidableEq I] in
theorem linearPolynomial_smul (a : k) (v : I → k) :
    linearPolynomial (a • v) = C a * linearPolynomial v := by
  simp only [linearPolynomial, Pi.smul_apply, smul_eq_mul, map_mul,
    Finset.mul_sum, mul_assoc]

/-- Linearization of `linearPolynomial`. -/
def linearPolynomialLinear : (I → k) →ₗ[k] MvPolynomial I k where
  toFun := linearPolynomial
  map_add' := linearPolynomial_add
  map_smul' a v := by
    rw [linearPolynomial_smul]
    simp [Algebra.smul_def]

omit [DecidableEq I] in
@[simp] theorem linearPolynomialLinear_apply (v : I → k) :
    linearPolynomialLinear v = linearPolynomial v := rfl

@[simp] theorem linearPolynomial_basisFun (i : I) :
    linearPolynomial ((Pi.basisFun k I) i) = X i := by
  rw [Pi.basisFun_apply]
  simp [linearPolynomial, Pi.single_apply]

/-- Polynomial substitution induced by an ambient linear equivalence. -/
def linearChangeHom (e : (I → k) ≃ₗ[k] (I → k)) :
    MvPolynomial I k →ₐ[k] MvPolynomial I k :=
  MvPolynomial.aeval (fun i ↦ linearPolynomial (e ((Pi.basisFun k I) i)))

@[simp] theorem linearChangeHom_X
    (e : (I → k) ≃ₗ[k] (I → k)) (i : I) :
    linearChangeHom e (X i) =
      linearPolynomial (e ((Pi.basisFun k I) i)) := by
  simp [linearChangeHom]

theorem linearChangeHom_linearPolynomial
    (e : (I → k) ≃ₗ[k] (I → k)) (v : I → k) :
    linearChangeHom e (linearPolynomial v) = linearPolynomial (e v) := by
  calc
    linearChangeHom e (linearPolynomial v) =
        ∑ i, C (v i) * linearPolynomial (e ((Pi.basisFun k I) i)) := by
      simp [linearPolynomial, linearChangeHom]
    _ = ∑ i, linearPolynomialLinear
        (v i • e ((Pi.basisFun k I) i)) := by
      apply Finset.sum_congr rfl
      intro i _hi
      exact (linearPolynomial_smul (v i)
        (e ((Pi.basisFun k I) i))).symm
    _ = linearPolynomialLinear
        (∑ i, v i • e ((Pi.basisFun k I) i)) := by
      rw [map_sum]
    _ = linearPolynomial (e v) := by
      change linearPolynomial (∑ i, v i • e ((Pi.basisFun k I) i)) =
        linearPolynomial (e v)
      have he := congrArg e ((Pi.basisFun k I).sum_repr v)
      simp only [map_sum, map_smul] at he
      exact congrArg linearPolynomial he

/-- The explicit polynomial automorphism induced by a linear equivalence. -/
def linearChangeEquiv (e : (I → k) ≃ₗ[k] (I → k)) :
    MvPolynomial I k ≃ₐ[k] MvPolynomial I k := by
  apply AlgEquiv.ofAlgHom (linearChangeHom e) (linearChangeHom e.symm)
  · apply MvPolynomial.algHom_ext
    intro i
    rw [AlgHom.comp_apply, linearChangeHom_X,
      linearChangeHom_linearPolynomial, e.apply_symm_apply,
      linearPolynomial_basisFun]
    rfl
  · apply MvPolynomial.algHom_ext
    intro i
    rw [AlgHom.comp_apply, linearChangeHom_X,
      linearChangeHom_linearPolynomial, e.symm_apply_apply,
      linearPolynomial_basisFun]
    rfl

@[simp] theorem linearChangeEquiv_linearPolynomial
    (e : (I → k) ≃ₗ[k] (I → k)) (v : I → k) :
    linearChangeEquiv e (linearPolynomial v) = linearPolynomial (e v) := by
  exact linearChangeHom_linearPolynomial e v

/-- The ideal generated by a labelled family of finite linear forms. -/
def linearFormIdeal {J : Type*} (row : J → I → k) :
    Ideal (MvPolynomial I k) :=
  Ideal.span (Set.range (fun j ↦ linearPolynomial (row j)))

/-- Coefficient vectors whose linear polynomials lie in an ideal. -/
def linearPolynomialPreimage
    (Q : Ideal (MvPolynomial I k)) : Submodule k (I → k) :=
  { carrier := {v | linearPolynomial v ∈ Q}
    zero_mem' := by simp
    add_mem' := by
      intro u v hu hv
      change linearPolynomial (u + v) ∈ Q
      rw [linearPolynomial_add]
      exact Q.add_mem hu hv
    smul_mem' := by
      intro a v hv
      change linearPolynomial (a • v) ∈ Q
      rw [linearPolynomial_smul]
      exact Q.mul_mem_left _ hv }

omit [DecidableEq I] in
theorem linearPolynomial_mem_linearFormIdeal_of_mem_span
    {J : Type*} (row : J → I → k) (v : I → k)
    (hv : v ∈ Submodule.span k (Set.range row)) :
    linearPolynomial v ∈ linearFormIdeal row := by
  let S := linearPolynomialPreimage (linearFormIdeal row)
  have hrange : Set.range row ⊆ (S : Set (I → k)) := by
    rintro _ ⟨j, rfl⟩
    change linearPolynomial (row j) ∈ linearFormIdeal row
    exact Ideal.subset_span ⟨j, rfl⟩
  exact Submodule.span_le.mpr hrange hv

omit [DecidableEq I] in
theorem linearFormIdeal_eq_basisIdeal
    {J : Type*} (row : J → I → k) :
    let W := Submodule.span k (Set.range row)
    let b := Module.finBasis k W
    linearFormIdeal row =
      Ideal.span (Set.range (fun i ↦ linearPolynomial (b i : I → k))) := by
  dsimp only
  let W := Submodule.span k (Set.range row)
  let b := Module.finBasis k W
  let Q : Ideal (MvPolynomial I k) :=
    Ideal.span (Set.range (fun i ↦ linearPolynomial (b i : I → k)))
  apply le_antisymm
  · rw [linearFormIdeal, Ideal.span_le]
    rintro _ ⟨j, rfl⟩
    let S := linearPolynomialPreimage Q
    have hb : Set.range (fun i ↦ (b i : I → k)) ⊆
        (S : Set (I → k)) := by
      rintro _ ⟨i, rfl⟩
      change linearPolynomial (b i : I → k) ∈ Q
      exact Ideal.subset_span ⟨i, rfl⟩
    have hW : W ≤ S := by
      intro x hx
      let xW : W := ⟨x, hx⟩
      have hrepr := b.sum_repr xW
      have hreprVal :
          ∑ i, (b.repr xW) i • (b i : I → k) = x := by
        calc
          ∑ i, (b.repr xW) i • (b i : I → k) =
              W.subtype (∑ i, (b.repr xW) i • b i) := by
            rw [map_sum]
            rfl
          _ = W.subtype xW := congrArg W.subtype hrepr
          _ = x := rfl
      rw [← hreprVal]
      apply S.sum_mem
      intro i _hi
      exact S.smul_mem _ (hb ⟨i, rfl⟩)
    have hj := hW (Submodule.subset_span ⟨j, rfl⟩)
    exact hj
  · rw [Ideal.span_le]
    rintro _ ⟨i, rfl⟩
    exact linearPolynomial_mem_linearFormIdeal_of_mem_span row
      (b i : I → k) (b i).2

/-- Every ideal generated by a finite-coordinate family of linear forms is
prime. -/
theorem linearFormIdeal_isPrime
    {J : Type*} (row : J → I → k) :
    (linearFormIdeal row).IsPrime := by
  classical
  let W := Submodule.span k (Set.range row)
  let r := Module.finrank k W
  let bW := Module.finBasis k W
  let family : Fin r → I → k := fun i ↦ (bW i : I → k)
  have hfamily : LinearIndependent k family := by
    exact bW.linearIndependent.map' W.subtype
      ((LinearMap.ker_eq_bot).2 W.subtype_injective)
  let bExt := Module.Basis.sumExtend hfamily
  let idx : (Fin r ⊕ Module.Basis.sumExtendIndex hfamily) ≃ I :=
    bExt.indexEquiv (Pi.basisFun k I)
  let bI : Module.Basis I k (I → k) := bExt.reindex idx
  let e : (I → k) ≃ₗ[k] (I → k) :=
    (Pi.basisFun k I).equiv bI (Equiv.refl I)
  let S : Set I := Set.range (fun i : Fin r ↦ idx (Sum.inl i))
  have he (i : Fin r) :
      e ((Pi.basisFun k I) (idx (Sum.inl i))) = family i := by
    dsimp [e]
    rw [Module.Basis.equiv_apply]
    simp only [Equiv.refl_apply]
    dsimp [bI]
    rw [Module.Basis.reindex_apply]
    have hidx : idx.symm (idx (Sum.inl i)) = Sum.inl i :=
      idx.symm_apply_apply (Sum.inl i)
    rw [hidx]
    change (Module.Basis.sumExtend hfamily) (Sum.inl i) = family i
    rw [Module.Basis.sumExtend, Module.Basis.reindex_apply]
    simp only [Equiv.symm_symm]
    exact Module.Basis.extend_apply_self _ _
  have hX (i : Fin r) :
      linearChangeEquiv e (X (idx (Sum.inl i))) =
        linearPolynomial (family i) := by
    change linearChangeHom e (X (idx (Sum.inl i))) = _
    rw [linearChangeHom_X, he]
  have hmap :
      Ideal.map (linearChangeEquiv e).toRingEquiv
          (coordinateVariableIdeal (k := k) S) =
        Ideal.span (Set.range (fun i ↦ linearPolynomial (family i))) := by
    rw [coordinateVariableIdeal, Ideal.map_span]
    congr 1
    ext q
    constructor
    · rintro ⟨x, ⟨_, ⟨i, rfl⟩, rfl⟩, rfl⟩
      exact ⟨i, (hX i).symm⟩
    · rintro ⟨i, rfl⟩
      refine ⟨X (idx (Sum.inl i)), ?_, ?_⟩
      · refine ⟨idx (Sum.inl i), ?_, rfl⟩
        exact ⟨i, rfl⟩
      · simpa using hX i
  letI : (coordinateVariableIdeal (k := k) S).IsPrime :=
    coordinateVariableIdeal_isPrime S
  have hprime : (Ideal.span (Set.range
      (fun i ↦ linearPolynomial (family i)))).IsPrime := by
    rw [← hmap]
    exact Ideal.map_isPrime_of_equiv (linearChangeEquiv e).toRingEquiv
  rw [linearFormIdeal_eq_basisIdeal row]
  simpa [W, bW, family] using hprime

end


end LinearFormIdeal

end RB31E2E
