import RB31EndToEnd.Algebra.FilteredInitialHeight
import RB31EndToEnd.Incidence.PinTriangularElimination
import Mathlib.Algebra.MvPolynomial.Equiv
import Mathlib.RingTheory.Ideal.KrullsHeightTheorem
import Mathlib.RingTheory.Polynomial.Quotient

/-!
# Primewise height contributed by private pin coordinates

On an angular away chart, `PinTriangularElimination` rewrites the two
compatibility equations of one active pin as

`private coordinate - expression in the retained coordinates`.

The algebraic content of “this pin contributes two” is therefore the
translated-coordinate lemma proved here.  Over any domain, any injectively
labelled family of `n` private variables, translated by coefficient-ring
elements, generates a prime ideal of height at least `n`.  The proof is an
explicit polynomial translation automorphism followed by the coordinate
prime chain from `FilteredInitialHeight`; all dimension estimates used below are proved there.

The final section packages the `n = 2` active-pin fibre and an
occurrence-indexed family with two disjoint private variables per occurrence.
It also gives a ring-equivalence transport lemma for applying the result after
quotienting by a prior prime and isolating the private variables.  No claim is
made that an arbitrary ideal admits such a private-variable presentation.
-/

namespace RB31E2E

namespace ActivePinPrimeHeight

noncomputable section

open MvPolynomial
open NullCellulePolynomial

/-! ## Translation of polynomial coordinates -/

/-- Simultaneously translate every polynomial variable by a coefficient. -/
def coordinateTranslationHom {k σ : Type*} [CommRing k] (a : σ → k) :
    MvPolynomial σ k →ₐ[k] MvPolynomial σ k :=
  MvPolynomial.aeval (fun x ↦ X x + C (a x))

@[simp]
theorem coordinateTranslationHom_X {k σ : Type*} [CommRing k]
    (a : σ → k) (x : σ) :
    coordinateTranslationHom a (X x) = X x + C (a x) := by
  simp [coordinateTranslationHom]

@[simp]
theorem coordinateTranslationHom_C {k σ : Type*} [CommRing k]
    (a : σ → k) (r : k) :
    coordinateTranslationHom a (C r) = C r := by
  simp [coordinateTranslationHom]

/-- Polynomial translation is an automorphism; translation by `-a` is its
inverse. -/
def coordinateTranslationEquiv {k σ : Type*} [CommRing k] (a : σ → k) :
    MvPolynomial σ k ≃ₐ[k] MvPolynomial σ k := by
  apply AlgEquiv.ofAlgHom
    (coordinateTranslationHom a)
    (coordinateTranslationHom (fun x ↦ -a x))
  · apply MvPolynomial.algHom_ext
    intro x
    simp [coordinateTranslationHom]
  · apply MvPolynomial.algHom_ext
    intro x
    simp [coordinateTranslationHom]

@[simp]
theorem coordinateTranslationEquiv_X {k σ : Type*} [CommRing k]
    (a : σ → k) (x : σ) :
    coordinateTranslationEquiv a (X x) = X x + C (a x) := by
  simp [coordinateTranslationEquiv]

@[simp]
theorem coordinateTranslationEquiv_C {k σ : Type*} [CommRing k]
    (a : σ → k) (r : k) :
    coordinateTranslationEquiv a (C r) = C r := by
  simp [coordinateTranslationEquiv]

/-! ## A translated coordinate prime of the expected height -/

/-- The ideal generated by `n` translated, injectively labelled coordinate
variables. -/
def translatedCoordinateIdeal {k σ : Type*} [CommRing k] {n : ℕ}
    (c : Fin n → σ) (a : σ → k) : Ideal (MvPolynomial σ k) :=
  Ideal.span (Set.range (fun j ↦ X (c j) - C (a (c j))))

/-- Translation identifies the translated-coordinate ideal with the image
of the corresponding ordinary coordinate ideal. -/
theorem translatedCoordinateIdeal_eq_map_coordinateVariableIdeal
    {k σ : Type*} [CommRing k] {n : ℕ}
    (c : Fin n → σ) (a : σ → k) :
    translatedCoordinateIdeal c a =
      Ideal.map (coordinateTranslationEquiv (fun x ↦ -a x)).toRingEquiv
        (coordinateVariableIdeal (k := k) (Set.range c)) := by
  rw [translatedCoordinateIdeal, coordinateVariableIdeal, Ideal.map_span]
  congr 1
  ext q
  constructor
  · rintro ⟨j, rfl⟩
    refine ⟨X (c j), ⟨c j, ⟨j, rfl⟩, rfl⟩, ?_⟩
    simp [sub_eq_add_neg]
  · rintro ⟨q, ⟨x, ⟨j, rfl⟩, rfl⟩, rfl⟩
    exact ⟨j, by simp [sub_eq_add_neg]⟩

/-- A translated family of independent coordinates still generates a prime
ideal. -/
theorem translatedCoordinateIdeal_isPrime
    {k σ : Type*} [CommRing k] [IsDomain k] {n : ℕ}
    (c : Fin n → σ) (a : σ → k) :
    (translatedCoordinateIdeal c a).IsPrime := by
  rw [translatedCoordinateIdeal_eq_map_coordinateVariableIdeal]
  letI : (coordinateVariableIdeal (k := k) (Set.range c)).IsPrime :=
    coordinateVariableIdeal_isPrime (k := k) (Set.range c)
  exact Ideal.map_isPrime_of_equiv
    (coordinateTranslationEquiv (fun x ↦ -a x)).toRingEquiv

/-- An injectively labelled translated coordinate family contributes at
least one unit of height per private variable. -/
theorem translatedCoordinateIdeal_height_ge_card
    {k σ : Type*} [CommRing k] [IsDomain k] {n : ℕ}
    (c : Fin n → σ) (hc : Function.Injective c) (a : σ → k) :
    (n : ℕ∞) ≤ (translatedCoordinateIdeal c a).height := by
  rw [translatedCoordinateIdeal_eq_map_coordinateVariableIdeal,
    (coordinateTranslationEquiv (fun x ↦ -a x)).toRingEquiv.height_map]
  exact coordinateVariableIdeal_height_ge_card (k := k) c hc

/-! ## One active pin: two private coordinates -/

/-- The normal-form ideal of one active pin after quotienting the prior
constraints and retaining only its two private polynomial coordinates. -/
def activePinRelationIdeal {k : Type*} [CommRing k] (a : Fin 2 → k) :
    Ideal (MvPolynomial (Fin 2) k) :=
  translatedCoordinateIdeal (fun j : Fin 2 ↦ j) a

theorem activePinRelationIdeal_isPrime
    {k : Type*} [CommRing k] [IsDomain k] (a : Fin 2 → k) :
    (activePinRelationIdeal a).IsPrime := by
  exact translatedCoordinateIdeal_isPrime (fun j : Fin 2 ↦ j) a

/-- The precise primewise fibre statement: after the previous prime has been
quotiented out, the two private relations of one active pin have height at
least two. -/
theorem activePinRelationIdeal_height_ge_two
    {k : Type*} [CommRing k] [IsDomain k] (a : Fin 2 → k) :
    (2 : ℕ∞) ≤ (activePinRelationIdeal a).height := by
  exact translatedCoordinateIdeal_height_ge_card
    (fun j : Fin 2 ↦ j) Function.injective_id a

/-! ## Adding the active pair above a prior prime -/

/-- Change only the coefficient ring by quotienting a prior prime. -/
def quotientCoefficientMap {R σ : Type*} [CommRing R] (P : Ideal R) :
    MvPolynomial σ R →+* MvPolynomial σ (R ⧸ P) :=
  MvPolynomial.map (Ideal.Quotient.mk P)

theorem quotientCoefficientMap_surjective
    {R σ : Type*} [CommRing R] (P : Ideal R) :
    Function.Surjective (quotientCoefficientMap (P := P) ( σ := σ)) := by
  exact MvPolynomial.map_surjective _ Ideal.Quotient.mk_surjective

theorem quotientCoefficientMap_ker
    {R σ : Type*} [CommRing R] (P : Ideal R) :
    RingHom.ker (quotientCoefficientMap (P := P) (σ := σ)) =
      Ideal.map (C : R →+* MvPolynomial σ R) P := by
  rw [quotientCoefficientMap, MvPolynomial.ker_map, Ideal.mk_ker]

/-- Extend a coefficient prime and then kill a selected set of polynomial
coordinates. -/
def basePrimeCoordinateIdeal {R σ : Type*} [CommRing R]
    (P : Ideal R) (S : Set σ) : Ideal (MvPolynomial σ R) :=
  Ideal.map (C : R →+* MvPolynomial σ R) P ⊔
    coordinateVariableIdeal (k := R) S

theorem quotientCoefficientMap_map_coordinateVariableIdeal
    {R σ : Type*} [CommRing R] (P : Ideal R) (S : Set σ) :
    Ideal.map (quotientCoefficientMap (P := P) (σ := σ))
        (coordinateVariableIdeal (k := R) S) =
      coordinateVariableIdeal (k := R ⧸ P) S := by
  rw [coordinateVariableIdeal, coordinateVariableIdeal, Ideal.map_span]
  congr 1
  ext q
  simp [quotientCoefficientMap]

/-- The extended-prime-plus-coordinates ideal is the inverse image of the
coordinate ideal over the quotient domain. -/
theorem basePrimeCoordinateIdeal_eq_comap
    {R σ : Type*} [CommRing R] (P : Ideal R) (S : Set σ) :
    basePrimeCoordinateIdeal P S =
      Ideal.comap (quotientCoefficientMap (P := P) (σ := σ))
        (coordinateVariableIdeal (k := R ⧸ P) S) := by
  rw [← quotientCoefficientMap_map_coordinateVariableIdeal P S,
    Ideal.comap_map_of_surjective _
      (quotientCoefficientMap_surjective (P := P) (σ := σ)),
    ← RingHom.ker_eq_comap_bot, quotientCoefficientMap_ker,
    basePrimeCoordinateIdeal, sup_comm]

/-- Every such lifted coordinate ideal is prime when the coefficient ideal
is prime. -/
theorem basePrimeCoordinateIdeal_isPrime
    {R σ : Type*} [CommRing R] (P : Ideal R) [P.IsPrime] (S : Set σ) :
    (basePrimeCoordinateIdeal P S).IsPrime := by
  rw [basePrimeCoordinateIdeal_eq_comap]
  letI : (coordinateVariableIdeal (k := R ⧸ P) S).IsPrime :=
    coordinateVariableIdeal_isPrime (k := R ⧸ P) S
  exact Ideal.comap_isPrime _ _

/-- Distinct coordinate prefixes remain strictly distinct after lifting
above a coefficient prime. -/
theorem basePrimeCoordinatePrefix_lt
    {R σ : Type*} [CommRing R] (P : Ideal R) [P.IsPrime]
    {n : ℕ} (c : Fin n → σ) (hc : Function.Injective c)
    {j l : Fin (n + 1)} (hjl : j < l) :
    basePrimeCoordinateIdeal P (coordinatePrefixSet c j) <
      basePrimeCoordinateIdeal P (coordinatePrefixSet c l) := by
  rw [basePrimeCoordinateIdeal_eq_comap,
    basePrimeCoordinateIdeal_eq_comap]
  have htarget := coordinatePrefixIdeal_lt
    (k := R ⧸ P) c hc hjl
  have hsurj := quotientCoefficientMap_surjective (P := P) (σ := σ)
  refine lt_of_le_of_ne (Ideal.comap_mono htarget.le) ?_
  intro heq
  exact htarget.ne
    ((Ideal.comap_injective_of_surjective _ hsurj) heq)

/-- Extension by constants contracts back to the original coefficient
ideal. -/
theorem comap_map_C_eq_self
    {R σ : Type*} [CommRing R] (P : Ideal R) :
    Ideal.comap (C : R →+* MvPolynomial σ R)
      (Ideal.map C P) = P := by
  classical
  ext r
  simp only [Ideal.mem_comap, MvPolynomial.mem_map_C_iff]
  constructor
  · intro h
    simpa using h 0
  · intro hr m
    rw [coeff_C]
    split_ifs
    · exact hr
    · exact P.zero_mem

/-- Over a Noetherian coefficient ring, extending a prime to a finite
polynomial ring preserves its height. -/
theorem height_map_C_eq
    {R σ : Type*} [CommRing R] [IsNoetherianRing R] [Finite σ]
    (P : Ideal R) [P.IsPrime] :
    (Ideal.map (C : R →+* MvPolynomial σ R) P).height = P.height := by
  let Pext : Ideal (MvPolynomial σ R) := Ideal.map C P
  letI : Pext.IsPrime := by
    simpa [Pext, basePrimeCoordinateIdeal, coordinateVariableIdeal] using
      (basePrimeCoordinateIdeal_isPrime ( σ := σ) P (∅ : Set σ))
  letI : Pext.LiesOver P := ⟨by
    change P = Ideal.comap (C : R →+* MvPolynomial σ R) Pext
    exact (comap_map_C_eq_self ( σ := σ) P).symm⟩
  have h := Ideal.height_eq_height_add_of_liesOver_of_hasGoingDown P Pext
  have hmap : Ideal.map
      (Ideal.Quotient.mk
        (Ideal.map (algebraMap R (MvPolynomial σ R)) P)) Pext = ⊥ := by
    change Ideal.map
      (Ideal.Quotient.mk
        (Ideal.map (C : R →+* MvPolynomial σ R) P))
      (Ideal.map C P) = ⊥
    exact Ideal.map_quotient_self _
  letI : (Ideal.map
      (algebraMap R (MvPolynomial σ R)) P).IsPrime := by
    simpa [Pext] using (inferInstance : Pext.IsPrime)
  rw [hmap, Ideal.height_bot, add_zero] at h
  exact h

/-- Before translation, adjoining both private coordinates above a prior
prime raises height by at least two. -/
theorem basePrimeCoordinateIdeal_height_ge_add_two
    {R : Type*} [CommRing R] [IsNoetherianRing R]
    (P : Ideal R) [P.IsPrime] :
    P.height + 2 ≤
      (basePrimeCoordinateIdeal P (Set.univ : Set (Fin 2))).height := by
  let c : Fin 2 → Fin 2 := fun j ↦ j
  let I : Fin 3 → Ideal (MvPolynomial (Fin 2) R) := fun j ↦
    basePrimeCoordinateIdeal P (coordinatePrefixSet c j)
  have h01 : I 0 < I 1 := by
    exact basePrimeCoordinatePrefix_lt P c Function.injective_id (by decide)
  have h12 : I 1 < I 2 := by
    exact basePrimeCoordinatePrefix_lt P c Function.injective_id (by decide)
  letI : (I 0).IsPrime :=
    basePrimeCoordinateIdeal_isPrime P (coordinatePrefixSet c 0)
  letI : (I 1).IsPrime :=
    basePrimeCoordinateIdeal_isPrime P (coordinatePrefixSet c 1)
  letI : (I 2).IsPrime :=
    basePrimeCoordinateIdeal_isPrime P (coordinatePrefixSet c 2)
  have hfirst := Ideal.primeHeight_add_one_le_of_lt h01
  have hsecond := Ideal.primeHeight_add_one_le_of_lt h12
  have hchain : (I 0).height + 2 ≤ (I 2).height := by
    rw [Ideal.height_eq_primeHeight, Ideal.height_eq_primeHeight]
    calc
      (I 0).primeHeight + 2 =
          ((I 0).primeHeight + 1) + 1 := by norm_num [add_assoc]
      _ ≤ (I 1).primeHeight + 1 := by
        simpa [add_assoc, add_comm, add_left_comm] using
          (add_le_add_right hfirst 1)
      _ ≤ (I 2).primeHeight := hsecond
  have hzero : I 0 = Ideal.map
      (C : R →+* MvPolynomial (Fin 2) R) P := by
    simp [I, c, coordinatePrefixSet, basePrimeCoordinateIdeal,
      coordinateVariableIdeal]
  have hlast : I 2 =
      basePrimeCoordinateIdeal P (Set.univ : Set (Fin 2)) := by
    change basePrimeCoordinateIdeal P
        (coordinatePrefixSet c (Fin.last 2)) = _
    rw [coordinatePrefixSet_last]
    simp [c]
  rw [hzero, hlast, height_map_C_eq ( σ := Fin 2) P] at hchain
  exact hchain

/-- Add a translated pair of active-pin relations above a prior coefficient
prime. -/
def primeWithActivePinIdeal {R : Type*} [CommRing R]
    (P : Ideal R) (a : Fin 2 → R) : Ideal (MvPolynomial (Fin 2) R) :=
  Ideal.map (C : R →+* MvPolynomial (Fin 2) R) P ⊔
    activePinRelationIdeal a

private theorem translation_map_map_C
    {R σ : Type*} [CommRing R] (P : Ideal R) (a : σ → R) :
    Ideal.map (coordinateTranslationEquiv a).toRingEquiv
        (Ideal.map (C : R →+* MvPolynomial σ R) P) =
      Ideal.map C P := by
  rw [show Ideal.map (coordinateTranslationEquiv a).toRingEquiv
        (Ideal.map (C : R →+* MvPolynomial σ R) P) =
      Ideal.map
        ((coordinateTranslationEquiv a).toRingEquiv.toRingHom.comp C) P by
        exact Ideal.map_map C
          (coordinateTranslationEquiv a).toRingEquiv.toRingHom]
  congr 1
  ext r
  simp

theorem primeWithActivePinIdeal_eq_map_basePrimeCoordinateIdeal
    {R : Type*} [CommRing R] (P : Ideal R) (a : Fin 2 → R) :
    primeWithActivePinIdeal P a =
      Ideal.map
        (coordinateTranslationEquiv (fun x ↦ -a x)).toRingEquiv
        (basePrimeCoordinateIdeal P (Set.univ : Set (Fin 2))) := by
  rw [primeWithActivePinIdeal, basePrimeCoordinateIdeal, Ideal.map_sup,
    translation_map_map_C]
  change _ ⊔ activePinRelationIdeal a = _ ⊔ _
  rw [activePinRelationIdeal,
    translatedCoordinateIdeal_eq_map_coordinateVariableIdeal]
  simp

theorem primeWithActivePinIdeal_isPrime
    {R : Type*} [CommRing R] (P : Ideal R) [P.IsPrime]
    (a : Fin 2 → R) :
    (primeWithActivePinIdeal P a).IsPrime := by
  rw [primeWithActivePinIdeal_eq_map_basePrimeCoordinateIdeal]
  letI : (basePrimeCoordinateIdeal P
      (Set.univ : Set (Fin 2))).IsPrime :=
    basePrimeCoordinateIdeal_isPrime P Set.univ
  exact Ideal.map_isPrime_of_equiv
    (coordinateTranslationEquiv (fun x ↦ -a x)).toRingEquiv

/-- Main increment theorem in private-coordinate normal form: adding one
active occurrence raises the height above the prior coefficient prime by at
least two. -/
theorem primeWithActivePinIdeal_height_ge_add_two
    {R : Type*} [CommRing R] [IsNoetherianRing R]
    (P : Ideal R) [P.IsPrime] (a : Fin 2 → R) :
    P.height + 2 ≤ (primeWithActivePinIdeal P a).height := by
  rw [primeWithActivePinIdeal_eq_map_basePrimeCoordinateIdeal,
    (coordinateTranslationEquiv (fun x ↦ -a x)).toRingEquiv.height_map]
  exact basePrimeCoordinateIdeal_height_ge_add_two P

/-- Quotient specialization: a prior prime ideal supplies a domain of
coefficients, and the active pin contributes height two over that quotient. -/
theorem quotient_activePinRelationIdeal_height_ge_two
    {R : Type*} [CommRing R] (P : Ideal R) [P.IsPrime]
    (a : Fin 2 → R ⧸ P) :
    (2 : ℕ∞) ≤ (activePinRelationIdeal a).height := by
  exact activePinRelationIdeal_height_ge_two a

/-- The same quotient fibre is prime, so the two-step coordinate chain can
be continued primewise. -/
theorem quotient_activePinRelationIdeal_isPrime
    {R : Type*} [CommRing R] (P : Ideal R) [P.IsPrime]
    (a : Fin 2 → R ⧸ P) :
    (activePinRelationIdeal a).IsPrime := by
  exact activePinRelationIdeal_isPrime a

/-! ## Two private variables for every occurrence -/

/-- Flatten an occurrence and one of its two private slots into the finite
index used by the coordinate-height theorem. -/
def occurrencePrivateVariable {m : ℕ} {σ : Type*}
    (pinVar : Fin m → Fin 2 → σ) : Fin (m * 2) → σ :=
  fun q ↦
    pinVar (finProdFinEquiv.symm q).1 (finProdFinEquiv.symm q).2

/-- All translated private-coordinate relations for `m` occurrences. -/
def occurrencePrivateRelationIdeal
    {k σ : Type*} [CommRing k] {m : ℕ}
    (pinVar : Fin m → Fin 2 → σ) (a : σ → k) :
    Ideal (MvPolynomial σ k) :=
  translatedCoordinateIdeal (occurrencePrivateVariable pinVar) a

theorem occurrencePrivateVariable_injective
    {m : ℕ} {σ : Type*} (pinVar : Fin m → Fin 2 → σ)
    (hpin : Function.Injective
      (fun q : Fin m × Fin 2 ↦ pinVar q.1 q.2)) :
    Function.Injective (occurrencePrivateVariable pinVar) := by
  intro q r hqr
  apply finProdFinEquiv.symm.injective
  exact hpin hqr

/-- Disjoint provenance variables give exactly two certified height units
per occurrence. -/
theorem occurrencePrivateRelationIdeal_height_ge_twice_card
    {k σ : Type*} [CommRing k] [IsDomain k] {m : ℕ}
    (pinVar : Fin m → Fin 2 → σ)
    (hpin : Function.Injective
      (fun q : Fin m × Fin 2 ↦ pinVar q.1 q.2))
    (a : σ → k) :
    (m * 2 : ℕ) ≤ (occurrencePrivateRelationIdeal pinVar a).height := by
  exact translatedCoordinateIdeal_height_ge_card
    (occurrencePrivateVariable pinVar)
    (occurrencePrivateVariable_injective pinVar hpin) a

theorem occurrencePrivateRelationIdeal_isPrime
    {k σ : Type*} [CommRing k] [IsDomain k] {m : ℕ}
    (pinVar : Fin m → Fin 2 → σ) (a : σ → k) :
    (occurrencePrivateRelationIdeal pinVar a).IsPrime := by
  exact translatedCoordinateIdeal_isPrime
    (occurrencePrivateVariable pinVar) a

/-! ## Transport from an explicit private-coordinate presentation -/

/-- Height transport for a concrete chart presentation.  The hypothesis is
an equality of explicit ideals under a supplied ring equivalence, not a new
properness or dimension principle. -/
theorem height_ge_two_of_equiv_to_activePinRelationIdeal
    {A k : Type*} [CommRing A] [CommRing k] [IsDomain k]
    (e : A ≃+* MvPolynomial (Fin 2) k) (J : Ideal A) (a : Fin 2 → k)
    (hJ : Ideal.map e J = activePinRelationIdeal a) :
    (2 : ℕ∞) ≤ J.height := by
  rw [← e.height_map J, hJ]
  exact activePinRelationIdeal_height_ge_two a

/-- Relative-height transport: an explicit private-coordinate presentation
of a prior prime together with one active-pin pair inherits the proved
height increment two. -/
theorem height_ge_add_two_of_equiv_to_primeWithActivePinIdeal
    {A R : Type*} [CommRing A] [CommRing R] [IsNoetherianRing R]
    (e : A ≃+* MvPolynomial (Fin 2) R) (J : Ideal A)
    (P : Ideal R) [P.IsPrime] (a : Fin 2 → R)
    (hJ : Ideal.map e J = primeWithActivePinIdeal P a) :
    P.height + 2 ≤ J.height := by
  rw [← e.height_map J, hJ]
  exact primeWithActivePinIdeal_height_ge_add_two P a

/-- Away-chart form specialized to the normalized two-relation ideal from
`PinTriangularElimination`.  Supplying the explicit coefficient/private-
variable ring equivalence closes the height-two step. -/
theorem normalizedPrivateRelationIdeal_height_ge_two_of_equiv
    {R A k : Type*} [CommRing R] [CommRing A] [CommRing k]
    [Algebra R A] [IsDomain k]
    (Z : Twist R) (p : Vec3 R) (i : Fin 3)
    [IsLocalization.Away (Z.1 i) A]
    (e : A ≃+* MvPolynomial (Fin 2) k) (a : Fin 2 → k)
    (hmap : Ideal.map e
      (PinTriangularElimination.normalizedPrivateRelationIdeal
        (A := A) Z p i) = activePinRelationIdeal a) :
    (2 : ℕ∞) ≤
      (PinTriangularElimination.normalizedPrivateRelationIdeal
        (A := A) Z p i).height := by
  exact height_ge_two_of_equiv_to_activePinRelationIdeal e _ a hmap

/-- Null-ideal sum form used by the incidence induction.  Once a concrete
away chart presents `prior ⊔ normalizedPrivateRelationIdeal` as a polynomial
ring in the two private pin coordinates over the quotient of a prior prime,
the height increases by two. -/
theorem prior_sup_normalizedPrivateRelationIdeal_height_ge_add_two_of_equiv
    {R A k : Type*} [CommRing R] [CommRing A] [CommRing k]
    [Algebra R A] [IsNoetherianRing k]
    (Z : Twist R) (p : Vec3 R) (i : Fin 3)
    [IsLocalization.Away (Z.1 i) A]
    (prior : Ideal A) (P : Ideal k) [P.IsPrime]
    (e : A ≃+* MvPolynomial (Fin 2) k) (a : Fin 2 → k)
    (hmap : Ideal.map e
      (prior ⊔
        PinTriangularElimination.normalizedPrivateRelationIdeal
          (A := A) Z p i) = primeWithActivePinIdeal P a) :
    P.height + 2 ≤
      (prior ⊔
        PinTriangularElimination.normalizedPrivateRelationIdeal
          (A := A) Z p i).height := by
  exact height_ge_add_two_of_equiv_to_primeWithActivePinIdeal
    e _ P a hmap

end

end ActivePinPrimeHeight

end RB31E2E
