import RB31EndToEnd.Incidence.UniversalChartHeightElimination
import RB31EndToEnd.Incidence.ActivePinPrimeHeight

/-!
# Universal active-pin height transfer

This file identifies the exact point at which the private-coordinate height
calculus meets the finite generic universal chart.

First, the base-changed chart ideal is split, without any hypothesis, into
the image of its active compatibility ideal and the image of its selected
null ideal.  The active summand is generated by the actual finite-generic
compatibility polynomials, with the occurrence/coordinate index retained.

Second, a generator-level coordinate presentation is enough to identify this
actual active summand with a provenance-labelled coordinate ideal.  Thus the
ideal equality (`hmap`) needed by the height machinery is a theorem, rather
than a separate ideal-level certificate.  The resulting relative theorem
says that the active occurrences add exactly the certified lower bound
`2 * active.card` above a selected-null coefficient prime.

After passage to `GenericPinCoefficientField`, the pin variables are
coefficients and the active relations are linear forms in the shared
body-twist variables.  The coordinate presentation therefore reduces the
height comparison to an explicit linear change of the twist coordinates.
-/

namespace RB31E2E

namespace UniversalActivePinHeightTransfer

noncomputable section

open MvPolynomial
open NullCellulePolynomial
open UniversalHomogeneousChart
open ActivePinPrimeHeight

/-! ## The actual finite-generic summands -/

/-- One actual active compatibility generator after extending the pin
parameters to their fraction field and finitely reindexing twist variables. -/
def finiteGenericActiveCompatibilityGenerator
    {V E : Type*} [Fintype V] [DecidableEq V] [DecidableEq E]
    (root : V) (src dst : E → V) (active : Finset E)
    (chart : active → Fin 3)
    (a : ActiveCompatibilityIndex active chart) :
    FiniteGenericRelativeRing root E :=
  finiteGenericChartHom root
    (activeCompatibilityGenerator root src dst active chart a)

/-- The finite-generic active ideal, defined as the image of the literal
universal active ideal. -/
def finiteGenericActiveCompatibilityIdeal
    {V E : Type*} [Fintype V] [DecidableEq V] [DecidableEq E]
    (root : V) (src dst : E → V) (active : Finset E)
    (chart : active → Fin 3) :
    Ideal (FiniteGenericRelativeRing root E) :=
  Ideal.map (finiteGenericChartHom root)
    (activeCompatibilityIdeal root src dst active chart)

/-- The finite-generic image of the selected null equations. -/
def finiteGenericSelectedNullIdeal
    {V E : Type*} [Fintype V] [DecidableEq V] [DecidableEq E]
    (root : V) (src dst : E → V) (active : Finset E)
    (selected : Finset active) :
    Ideal (FiniteGenericRelativeRing root E) :=
  Ideal.map (finiteGenericChartHom root)
    (Ideal.span (selectedNullGeneratorSet root src dst active selected))

/-- The active image is generated by the actual finite-generic compatibility
polynomials, not by an abstract replacement family. -/
theorem finiteGenericActiveCompatibilityIdeal_eq_span_range
    {V E : Type*} [Fintype V] [DecidableEq V] [DecidableEq E]
    (root : V) (src dst : E → V) (active : Finset E)
    (chart : active → Fin 3) :
    finiteGenericActiveCompatibilityIdeal root src dst active chart =
      Ideal.span (Set.range
        (finiteGenericActiveCompatibilityGenerator
          root src dst active chart)) := by
  rw [finiteGenericActiveCompatibilityIdeal, activeCompatibilityIdeal,
    Ideal.map_span]
  congr 1
  ext f
  constructor
  · rintro ⟨g, ⟨a, rfl⟩, rfl⟩
    exact ⟨a, rfl⟩
  · rintro ⟨a, rfl⟩
    exact ⟨activeCompatibilityGenerator root src dst active chart a,
      ⟨a, rfl⟩, rfl⟩

/-- Exact base-changed decomposition of the universal chart ideal. -/
theorem finiteGenericUniversalChartIdeal_eq_active_sup_selectedNull
    {V E : Type*} [Fintype V] [DecidableEq V] [DecidableEq E]
    (root : V) (src dst : E → V) (active : Finset E)
    (chart : active → Fin 3) (selected : Finset active) :
    finiteGenericUniversalChartIdeal root src dst active chart selected =
      finiteGenericActiveCompatibilityIdeal root src dst active chart ⊔
        finiteGenericSelectedNullIdeal root src dst active selected := by
  rw [finiteGenericUniversalChartIdeal, universalChartIdeal,
    universalChartGeneratorSet, Ideal.span_union, Ideal.map_sup]
  rfl

/-! ## A general relative coordinate-height lemma -/

/-- Adjoining an injectively labelled finite family of polynomial
coordinates above a coefficient prime raises height by at least the size of
the family.  This is the all-cardinalities version of the two-coordinate
lemma in `ActivePinPrimeHeight`. -/
theorem basePrimeCoordinateIdeal_height_ge_add_card
    {R σ : Type*} [CommRing R] [IsNoetherianRing R] [Finite σ]
    (P : Ideal R) [P.IsPrime] {n : ℕ}
    (c : Fin n → σ) (hc : Function.Injective c) :
    P.height + n ≤
      (basePrimeCoordinateIdeal P (Set.range c)).height := by
  let I : Fin (n + 1) → Ideal (MvPolynomial σ R) := fun j ↦
    basePrimeCoordinateIdeal P (coordinatePrefixSet c j)
  have hprime (j : Fin (n + 1)) : (I j).IsPrime := by
    dsimp [I]
    exact basePrimeCoordinateIdeal_isPrime P (coordinatePrefixSet c j)
  have hstep {j l : Fin (n + 1)} (hjl : j < l) : I j < I l := by
    exact basePrimeCoordinatePrefix_lt P c hc hjl
  have hprefix : ∀ j : Fin (n + 1),
      (I 0).primeHeight + j.1 ≤ (I j).primeHeight := by
    intro j
    induction j using Fin.induction with
    | zero => simp
    | succ j ih =>
        letI : (I (Fin.castSucc j)).IsPrime := hprime (Fin.castSucc j)
        letI : (I j.succ).IsPrime := hprime j.succ
        have hlt : I (Fin.castSucc j) < I j.succ := by
          apply hstep
          simp
        have hone := Ideal.primeHeight_add_one_le_of_lt hlt
        calc
          (I 0).primeHeight + (j.succ.1 : ℕ∞) =
              ((I 0).primeHeight + (j.1 : ℕ∞)) + 1 := by
                simp [add_assoc]
          _ ≤ (I (Fin.castSucc j)).primeHeight + 1 := by
                simpa [add_assoc, add_comm, add_left_comm] using
                  (add_le_add_right ih 1)
          _ ≤ (I j.succ).primeHeight := hone
  have hzero : I 0 =
      Ideal.map (C : R →+* MvPolynomial σ R) P := by
    simp [I, coordinatePrefixSet, basePrimeCoordinateIdeal,
      coordinateVariableIdeal]
  have hlast : I (Fin.last n) =
      basePrimeCoordinateIdeal P (Set.range c) := by
    change basePrimeCoordinateIdeal P
      (coordinatePrefixSet c (Fin.last n)) = _
    rw [coordinatePrefixSet_last]
  letI : (I 0).IsPrime := hprime 0
  letI : (I (Fin.last n)).IsPrime := hprime (Fin.last n)
  have h := hprefix (Fin.last n)
  rw [← Ideal.height_eq_primeHeight,
    ← Ideal.height_eq_primeHeight, hzero, hlast,
    height_map_C_eq ( σ := σ) P] at h
  simpa using h

/-! ## Provenance-coordinate presentation of the actual active ideal -/

/-- The canonical private coordinate occupied by one active compatibility
provenance label; `ρ` indexes all remaining twist coordinates. -/
def activePrivateCoordinate
    {E ρ : Type*} [DecidableEq E] {active : Finset E}
    {chart : active → Fin 3} :
    ActiveCompatibilityIndex active chart →
      ActiveCompatibilityIndex active chart ⊕ ρ :=
  Sum.inl

/-- A generator-level coordinate presentation proves the desired ideal map.
No ideal equality is assumed. -/
theorem map_finiteGenericActiveCompatibilityIdeal_eq_coordinateIdeal
    {V E R ρ : Type*} [Fintype V] [DecidableEq V] [DecidableEq E]
    [CommRing R]
    (root : V) (src dst : E → V) (active : Finset E)
    (chart : active → Fin 3)
    (e : FiniteGenericRelativeRing root E ≃+*
      MvPolynomial (ActiveCompatibilityIndex active chart ⊕ ρ)
        R)
    (hgenerator : ∀ a : ActiveCompatibilityIndex active chart,
      e (finiteGenericActiveCompatibilityGenerator
        root src dst active chart a) = X (activePrivateCoordinate a)) :
    Ideal.map e
        (finiteGenericActiveCompatibilityIdeal
          root src dst active chart) =
      coordinateVariableIdeal
        (k := R)
        (Set.range (activePrivateCoordinate ( ρ := ρ))) := by
  rw [finiteGenericActiveCompatibilityIdeal_eq_span_range,
    Ideal.map_span, coordinateVariableIdeal]
  congr 1
  ext f
  constructor
  · rintro ⟨g, ⟨a, rfl⟩, rfl⟩
    exact ⟨activePrivateCoordinate a, ⟨a, rfl⟩, (hgenerator a).symm⟩
  · rintro ⟨_, ⟨a, rfl⟩, rfl⟩
    exact ⟨finiteGenericActiveCompatibilityGenerator
        root src dst active chart a,
      ⟨a, rfl⟩, hgenerator a⟩

/-- Under the same concrete coordinate presentation, the actual active
summand has height at least two per active occurrence. -/
theorem finiteGenericActiveCompatibilityIdeal_height_ge_twice_card
    {V E ρ : Type*} [Fintype V] [DecidableEq V] [DecidableEq E]
    (root : V) (src dst : E → V) (active : Finset E)
    (chart : active → Fin 3)
    (e : FiniteGenericRelativeRing root E ≃+*
      MvPolynomial (ActiveCompatibilityIndex active chart ⊕ ρ)
        (GenericPinCoefficientField E))
    (hgenerator : ∀ a : ActiveCompatibilityIndex active chart,
      e (finiteGenericActiveCompatibilityGenerator
        root src dst active chart a) = X (activePrivateCoordinate a)) :
    (2 * active.card : ℕ) ≤
      (finiteGenericActiveCompatibilityIdeal
        root src dst active chart).height := by
  let b : ActiveCompatibilityIndex active chart ≃
      Fin (Fintype.card (ActiveCompatibilityIndex active chart)) :=
    Fintype.equivFin _
  let c : Fin (Fintype.card (ActiveCompatibilityIndex active chart)) →
      ActiveCompatibilityIndex active chart ⊕ ρ :=
    fun j ↦ activePrivateCoordinate (b.symm j)
  have hc : Function.Injective c := by
    exact Function.Injective.comp Sum.inl_injective b.symm.injective
  have hrange : Set.range c =
      Set.range (activePrivateCoordinate ( ρ := ρ)) := by
    ext x
    constructor
    · rintro ⟨j, rfl⟩
      exact ⟨b.symm j, rfl⟩
    · rintro ⟨a, rfl⟩
      exact ⟨b a, by simp [c, b]⟩
  rw [← e.height_map,
    map_finiteGenericActiveCompatibilityIdeal_eq_coordinateIdeal
      root src dst active chart e hgenerator,
    ← hrange, ← card_activeCompatibilityIndex]
  exact coordinateVariableIdeal_height_ge_card
    (k := GenericPinCoefficientField E) c hc

/-- Residual-free form of the preceding `hmap`: when all remaining twist
coordinates have been absorbed into the coefficient ring, the active
generators become the full coordinate ideal. -/
theorem map_finiteGenericActiveCompatibilityIdeal_eq_coordinateIdeal_univ
    {V E R : Type*} [Fintype V] [DecidableEq V] [DecidableEq E]
    [CommRing R]
    (root : V) (src dst : E → V) (active : Finset E)
    (chart : active → Fin 3)
    (e : FiniteGenericRelativeRing root E ≃+*
      MvPolynomial (ActiveCompatibilityIndex active chart) R)
    (hgenerator : ∀ a : ActiveCompatibilityIndex active chart,
      e (finiteGenericActiveCompatibilityGenerator
        root src dst active chart a) = X a) :
    Ideal.map e
        (finiteGenericActiveCompatibilityIdeal
          root src dst active chart) =
      coordinateVariableIdeal
        (k := R) (Set.univ : Set (ActiveCompatibilityIndex active chart)) := by
  rw [finiteGenericActiveCompatibilityIdeal_eq_span_range,
    Ideal.map_span, coordinateVariableIdeal]
  congr 1
  ext f
  constructor
  · rintro ⟨g, ⟨a, rfl⟩, rfl⟩
    exact ⟨a, Set.mem_univ a, (hgenerator a).symm⟩
  · rintro ⟨a, _ha, rfl⟩
    exact ⟨finiteGenericActiveCompatibilityGenerator
        root src dst active chart a,
      ⟨a, rfl⟩, hgenerator a⟩

/-! ## Primewise relative height, without a selected-null presentation -/

/-- The coefficient prime below a prime of a coordinate presentation.  This
is a genuine contraction, so primality is inherited automatically. -/
def coefficientContraction
    {V E R : Type*} [Fintype V] [DecidableEq V] [DecidableEq E]
    [CommRing R]
    {root : V} {active : Finset E} {chart : active → Fin 3}
    (e : FiniteGenericRelativeRing root E ≃+*
      MvPolynomial (ActiveCompatibilityIndex active chart) R)
    (Q : Ideal (FiniteGenericRelativeRing root E)) : Ideal R :=
  Ideal.comap (C : R →+*
    MvPolynomial (ActiveCompatibilityIndex active chart) R)
    (Ideal.map e Q)

/-- Parameter-free primewise increment after an explicit generator-level
coordinate change: every prime over the full chart has at least two height
units per active occurrence above its coefficient contraction.  No
presentation of the selected-null ideal and no ideal-level `hmap` is
assumed. -/
theorem prime_height_ge_coefficientContraction_add_twice_card
    {V E R : Type*} [Fintype V] [DecidableEq V] [DecidableEq E]
    [CommRing R] [IsNoetherianRing R]
    (root : V) (src dst : E → V) (active : Finset E)
    (chart : active → Fin 3) (selected : Finset active)
    (e : FiniteGenericRelativeRing root E ≃+*
      MvPolynomial (ActiveCompatibilityIndex active chart) R)
    (hgenerator : ∀ a : ActiveCompatibilityIndex active chart,
      e (finiteGenericActiveCompatibilityGenerator
        root src dst active chart a) = X a)
    (Q : Ideal (FiniteGenericRelativeRing root E)) [Q.IsPrime]
    (hQ : finiteGenericUniversalChartIdeal
      root src dst active chart selected ≤ Q) :
    (coefficientContraction e Q).height + (2 * active.card : ℕ) ≤
      Q.height := by
  let Q' : Ideal (MvPolynomial
      (ActiveCompatibilityIndex active chart) R) := Ideal.map e Q
  let P : Ideal R := coefficientContraction e Q
  letI : Q'.IsPrime := by
    dsimp [Q']
    exact Ideal.map_isPrime_of_equiv e
  letI : P.IsPrime := by
    dsimp [P, coefficientContraction]
    exact Ideal.comap_isPrime _ _
  have hactive : finiteGenericActiveCompatibilityIdeal
      root src dst active chart ≤ Q := by
    apply le_trans _ hQ
    rw [finiteGenericUniversalChartIdeal_eq_active_sup_selectedNull]
    exact le_sup_left
  have hcoordinate : coordinateVariableIdeal
      (k := R) (Set.univ : Set (ActiveCompatibilityIndex active chart)) ≤ Q' := by
    rw [← map_finiteGenericActiveCompatibilityIdeal_eq_coordinateIdeal_univ
      root src dst active chart e hgenerator]
    exact Ideal.map_mono hactive
  have hbase : basePrimeCoordinateIdeal P
      (Set.univ : Set (ActiveCompatibilityIndex active chart)) ≤ Q' := by
    rw [basePrimeCoordinateIdeal]
    apply sup_le
    · change Ideal.map (C : R →+*
          MvPolynomial (ActiveCompatibilityIndex active chart) R)
          (Ideal.comap C Q') ≤ Q'
      exact Ideal.map_comap_le
    · exact hcoordinate
  let b : ActiveCompatibilityIndex active chart ≃
      Fin (Fintype.card (ActiveCompatibilityIndex active chart)) :=
    Fintype.equivFin _
  let c : Fin (Fintype.card (ActiveCompatibilityIndex active chart)) →
      ActiveCompatibilityIndex active chart := b.symm
  have hc : Function.Injective c := b.symm.injective
  have hrange : Set.range c =
      (Set.univ : Set (ActiveCompatibilityIndex active chart)) := by
    exact Set.range_eq_univ.mpr b.symm.surjective
  have hbaseHeight : P.height +
      (Fintype.card (ActiveCompatibilityIndex active chart) : ℕ) ≤
      (basePrimeCoordinateIdeal P
        (Set.univ : Set (ActiveCompatibilityIndex active chart))).height := by
    rw [← hrange]
    exact basePrimeCoordinateIdeal_height_ge_add_card P c hc
  letI : (basePrimeCoordinateIdeal P
      (Set.univ : Set (ActiveCompatibilityIndex active chart))).IsPrime :=
    basePrimeCoordinateIdeal_isPrime P Set.univ
  have hmono :
      (basePrimeCoordinateIdeal P
        (Set.univ : Set (ActiveCompatibilityIndex active chart))).height ≤
        Q'.height := by
    rw [Ideal.height_eq_primeHeight, Ideal.height_eq_primeHeight]
    exact Ideal.primeHeight_mono hbase
  calc
    (coefficientContraction e Q).height + (2 * active.card : ℕ) =
        P.height +
          (Fintype.card (ActiveCompatibilityIndex active chart) : ℕ) := by
            rw [card_activeCompatibilityIndex]
    _ ≤ (basePrimeCoordinateIdeal P
          (Set.univ : Set (ActiveCompatibilityIndex active chart))).height :=
      hbaseHeight
    _ ≤ Q'.height := hmono
    _ = Q.height := by
      exact e.height_map Q

/-! ## Relative transfer above the selected-null prime -/

/-- If a concrete twist-coordinate change isolates all active compatibility
generators as the full provenance-indexed polynomial-variable family, and
the selected-null prior becomes a coefficient prime, then the actual full
universal chart ideal maps to the corresponding
`basePrimeCoordinateIdeal`.  This is the application-level `hmap`. -/
theorem map_finiteGenericUniversalChartIdeal_eq_basePrimeCoordinateIdeal
    {V E R : Type*} [Fintype V] [DecidableEq V] [DecidableEq E]
    [CommRing R]
    (root : V) (src dst : E → V) (active : Finset E)
    (chart : active → Fin 3) (selected : Finset active)
    (e : FiniteGenericRelativeRing root E ≃+*
      MvPolynomial (ActiveCompatibilityIndex active chart) R)
    (P : Ideal R)
    (hprior : Ideal.map e
      (finiteGenericSelectedNullIdeal root src dst active selected) =
        Ideal.map (C : R →+*
          MvPolynomial (ActiveCompatibilityIndex active chart) R) P)
    (hgenerator : ∀ a : ActiveCompatibilityIndex active chart,
      e (finiteGenericActiveCompatibilityGenerator
        root src dst active chart a) = X a) :
    Ideal.map e
        (finiteGenericUniversalChartIdeal
          root src dst active chart selected) =
      basePrimeCoordinateIdeal P
        (Set.univ : Set (ActiveCompatibilityIndex active chart)) := by
  rw [finiteGenericUniversalChartIdeal_eq_active_sup_selectedNull,
    Ideal.map_sup, hprior, basePrimeCoordinateIdeal, sup_comm]
  congr 1
  rw [finiteGenericActiveCompatibilityIdeal_eq_span_range,
    Ideal.map_span, coordinateVariableIdeal]
  congr 1
  ext f
  constructor
  · rintro ⟨g, ⟨a, rfl⟩, rfl⟩
    exact ⟨a, Set.mem_univ a, (hgenerator a).symm⟩
  · rintro ⟨a, _ha, rfl⟩
    exact ⟨finiteGenericActiveCompatibilityGenerator
        root src dst active chart a,
      ⟨a, rfl⟩, hgenerator a⟩

/-- End-to-end relative active-height theorem.  Once the displayed
generator-level change of coordinates has been constructed, active
occurrences contribute `2 * active.card` height above the selected-null
coefficient prime; no separate ideal-map hypothesis remains. -/
theorem finiteGenericUniversalChartIdeal_height_ge_prior_add_twice_card
    {V E R : Type*} [Fintype V] [DecidableEq V] [DecidableEq E]
    [CommRing R] [IsNoetherianRing R]
    (root : V) (src dst : E → V) (active : Finset E)
    (chart : active → Fin 3) (selected : Finset active)
    (e : FiniteGenericRelativeRing root E ≃+*
      MvPolynomial (ActiveCompatibilityIndex active chart) R)
    (P : Ideal R) [P.IsPrime]
    (hprior : Ideal.map e
      (finiteGenericSelectedNullIdeal root src dst active selected) =
        Ideal.map (C : R →+*
          MvPolynomial (ActiveCompatibilityIndex active chart) R) P)
    (hgenerator : ∀ a : ActiveCompatibilityIndex active chart,
      e (finiteGenericActiveCompatibilityGenerator
        root src dst active chart a) = X a) :
    P.height + (2 * active.card : ℕ) ≤
      (finiteGenericUniversalChartIdeal
        root src dst active chart selected).height := by
  let b : ActiveCompatibilityIndex active chart ≃
      Fin (Fintype.card (ActiveCompatibilityIndex active chart)) :=
    Fintype.equivFin _
  let c : Fin (Fintype.card (ActiveCompatibilityIndex active chart)) →
      ActiveCompatibilityIndex active chart := b.symm
  have hc : Function.Injective c := b.symm.injective
  have hrange : Set.range c =
      (Set.univ : Set (ActiveCompatibilityIndex active chart)) := by
    exact Set.range_eq_univ.mpr b.symm.surjective
  rw [← e.height_map,
    map_finiteGenericUniversalChartIdeal_eq_basePrimeCoordinateIdeal
      root src dst active chart selected e P hprior hgenerator,
    ← hrange, ← card_activeCompatibilityIndex]
  exact basePrimeCoordinateIdeal_height_ge_add_card P c hc

end

end UniversalActivePinHeightTransfer

end RB31E2E
