import RB31EndToEnd.Incidence.UniversalHomogeneousChart
import Mathlib.RingTheory.GradedAlgebra.Homogeneous.Ideal

/-!
# Ideals on a universal incidence chart

This file packages the homogeneous equations from
`UniversalHomogeneousChart` into provenance-retaining generator sets and
ideals.  A chart chooses one angular coordinate for every active occurrence;
the linear part retains exactly the other two compatibility coordinates.
A separately selected subfamily of active occurrences contributes its
quadratic Split--Klein null equations.

The resulting ideal is homogeneous for the standard grading in the outer
grounded-twist variables.  Every concrete `IsIncidenceRealization` annihilates
the ideal under `realChartEvaluation`.  No denominator inversion, triangular
solution formula, height estimate, or elimination statement is used here.
-/

namespace RB31E2E

namespace UniversalHomogeneousChart

noncomputable section

open MvPolynomial

attribute [local instance] MvPolynomial.gradedAlgebra

/-! ## Provenance indices and generator sets -/

/-- After choosing the angular chart coordinate `i`, these are precisely the
other two compatibility coordinates. -/
abbrev OtherCompatibilityCoordinate (i : Fin 3) :=
  {j : Fin 3 // j ≠ i}

/-- Provenance for the two retained linear equations at every active
occurrence. -/
abbrev ActiveCompatibilityIndex {E : Type*} [DecidableEq E]
    (active : Finset E) (chart : active → Fin 3) :=
  Σ e : active, OtherCompatibilityCoordinate (chart e)

/-- The compatibility polynomial indexed by an active occurrence and one of
the two coordinates different from its chosen angular chart coordinate. -/
def activeCompatibilityGenerator
    {V E : Type*} [DecidableEq V] [DecidableEq E]
    (root : V) (src dst : E → V) (active : Finset E)
    (chart : active → Fin 3)
    (a : ActiveCompatibilityIndex active chart) :
    RelativeRing root E :=
  universalCompatibilityCoordinate root src dst a.1.1 a.2.1

/-- All retained degree-one compatibility equations, with occurrence and
coordinate provenance kept in the range index. -/
def activeCompatibilityGeneratorSet
    {V E : Type*} [DecidableEq V] [DecidableEq E]
    (root : V) (src dst : E → V) (active : Finset E)
    (chart : active → Fin 3) : Set (RelativeRing root E) :=
  Set.range (activeCompatibilityGenerator root src dst active chart)

/-- The ideal generated by the two retained compatibility coordinates at
each active occurrence. -/
def activeCompatibilityIdeal
    {V E : Type*} [DecidableEq V] [DecidableEq E]
    (root : V) (src dst : E → V) (active : Finset E)
    (chart : active → Fin 3) : Ideal (RelativeRing root E) :=
  Ideal.span (activeCompatibilityGeneratorSet root src dst active chart)

/-- A selected occurrence is active by construction; no later subset proof
is needed to use its incidence equation. -/
abbrev SelectedOccurrence {E : Type*} [DecidableEq E]
    (active : Finset E) (selected : Finset active) :=
  {e : active // e ∈ selected}

/-- The degree-two null equation carrying the provenance of one selected
active occurrence. -/
def selectedNullGenerator
    {V E : Type*} [DecidableEq V] [DecidableEq E]
    (root : V) (src dst : E → V) (active : Finset E)
    (selected : Finset active) (e : SelectedOccurrence active selected) :
    RelativeRing root E :=
  universalNullEquation root src dst e.1.1

/-- The selected family of quadratic Split--Klein null equations. -/
def selectedNullGeneratorSet
    {V E : Type*} [DecidableEq V] [DecidableEq E]
    (root : V) (src dst : E → V) (active : Finset E)
    (selected : Finset active) : Set (RelativeRing root E) :=
  Set.range (selectedNullGenerator root src dst active selected)

/-- The complete chart generator set: two linear compatibility equations per
active occurrence and one quadratic null equation per selected occurrence. -/
def universalChartGeneratorSet
    {V E : Type*} [DecidableEq V] [DecidableEq E]
    (root : V) (src dst : E → V) (active : Finset E)
    (chart : active → Fin 3) (selected : Finset active) :
    Set (RelativeRing root E) :=
  activeCompatibilityGeneratorSet root src dst active chart ∪
    selectedNullGeneratorSet root src dst active selected

/-- The universal homogeneous chart ideal. -/
def universalChartIdeal
    {V E : Type*} [DecidableEq V] [DecidableEq E]
    (root : V) (src dst : E → V) (active : Finset E)
    (chart : active → Fin 3) (selected : Finset active) :
    Ideal (RelativeRing root E) :=
  Ideal.span
    (universalChartGeneratorSet root src dst active chart selected)

/-! ## Standard twist homogeneity -/

/-- Every retained compatibility generator has twist degree one. -/
theorem activeCompatibilityGenerator_isHomogeneous_one
    {V E : Type*} [DecidableEq V] [DecidableEq E]
    (root : V) (src dst : E → V) (active : Finset E)
    (chart : active → Fin 3)
    (a : ActiveCompatibilityIndex active chart) :
    (activeCompatibilityGenerator root src dst active chart a).IsHomogeneous 1 := by
  exact universalCompatibilityCoordinate_isHomogeneous_one
    root src dst a.1.1 a.2.1

/-- The linear active-compatibility ideal is homogeneous for the standard
grading in the outer twist variables. -/
theorem activeCompatibilityIdeal_isHomogeneous
    {V E : Type*} [DecidableEq V] [DecidableEq E]
    (root : V) (src dst : E → V) (active : Finset E)
    (chart : active → Fin 3) :
    (activeCompatibilityIdeal root src dst active chart).IsHomogeneous
      (MvPolynomial.homogeneousSubmodule
        (GroundedTwistVariable root) (PinParameterRing E)) := by
  apply Ideal.homogeneous_span
    (MvPolynomial.homogeneousSubmodule
      (GroundedTwistVariable root) (PinParameterRing E))
    (activeCompatibilityGeneratorSet root src dst active chart)
  intro f hf
  obtain ⟨a, rfl⟩ := hf
  exact ⟨1, activeCompatibilityGenerator_isHomogeneous_one
    root src dst active chart a⟩

/-- Every selected null generator has twist degree two. -/
theorem selectedNullGenerator_isHomogeneous_two
    {V E : Type*} [DecidableEq V] [DecidableEq E]
    (root : V) (src dst : E → V) (active : Finset E)
    (selected : Finset active) (e : SelectedOccurrence active selected) :
    (selectedNullGenerator root src dst active selected e).IsHomogeneous 2 := by
  exact universalNullEquation_isHomogeneous_two root src dst e.1.1

/-- Every generator of the complete chart ideal is homogeneous, with its
degree determined by its provenance branch. -/
theorem universalChartGeneratorSet_isHomogeneous
    {V E : Type*} [DecidableEq V] [DecidableEq E]
    (root : V) (src dst : E → V) (active : Finset E)
    (chart : active → Fin 3) (selected : Finset active) :
    ∀ f ∈ universalChartGeneratorSet root src dst active chart selected,
      ∃ d : ℕ, f.IsHomogeneous d := by
  intro f hf
  rcases hf with hf | hf
  · obtain ⟨a, rfl⟩ := hf
    exact ⟨1, activeCompatibilityGenerator_isHomogeneous_one
      root src dst active chart a⟩
  · obtain ⟨e, rfl⟩ := hf
    exact ⟨2, selectedNullGenerator_isHomogeneous_two
      root src dst active selected e⟩

/-- The full linear-plus-quadratic chart ideal is standard homogeneous in
the grounded-twist variables. -/
theorem universalChartIdeal_isHomogeneous
    {V E : Type*} [DecidableEq V] [DecidableEq E]
    (root : V) (src dst : E → V) (active : Finset E)
    (chart : active → Fin 3) (selected : Finset active) :
    (universalChartIdeal root src dst active chart selected).IsHomogeneous
      (MvPolynomial.homogeneousSubmodule
        (GroundedTwistVariable root) (PinParameterRing E)) := by
  apply Ideal.homogeneous_span
    (MvPolynomial.homogeneousSubmodule
      (GroundedTwistVariable root) (PinParameterRing E))
    (universalChartGeneratorSet root src dst active chart selected)
  exact universalChartGeneratorSet_isHomogeneous
    root src dst active chart selected

/-! ## Semantic annihilation by actual incidence realizations -/

/-- Every actual incidence realization annihilates the retained linear
compatibility ideal, for every chart choice. -/
theorem IsIncidenceRealization.realChartEvaluation_annihilates_activeCompatibilityIdeal
    {V E : Type*} [DecidableEq V] [DecidableEq E]
    {src dst : E → V} {active : Finset E}
    {p : E → Vec3 ℝ} {Y : V → Twist ℝ}
    (hY : SparseNullIncidence.IsIncidenceRealization src dst active p Y)
    (root : V) (chart : active → Fin 3) :
    activeCompatibilityIdeal root src dst active chart ≤
      RingHom.ker (realChartEvaluation root p Y) := by
  rw [activeCompatibilityIdeal, Ideal.span_le]
  rintro _ ⟨a, rfl⟩
  change realChartEvaluation root p Y
      (activeCompatibilityGenerator root src dst active chart a) = 0
  exact IsIncidenceRealization.realChartEvaluation_compatibility_eq_zero
    hY root a.1 a.2.1

/-- Every actual incidence realization annihilates all selected quadratic
null generators. -/
theorem IsIncidenceRealization.realChartEvaluation_annihilates_selectedNullGeneratorSet
    {V E : Type*} [DecidableEq V] [DecidableEq E]
    {src dst : E → V} {active : Finset E}
    {p : E → Vec3 ℝ} {Y : V → Twist ℝ}
    (hY : SparseNullIncidence.IsIncidenceRealization src dst active p Y)
    (root : V) (selected : Finset active) :
    ∀ f ∈ selectedNullGeneratorSet root src dst active selected,
      realChartEvaluation root p Y f = 0 := by
  intro _ hf
  obtain ⟨e, rfl⟩ := hf
  exact IsIncidenceRealization.realChartEvaluation_null_eq_zero hY root e.1

/-- End-to-end semantic bridge for this layer: every concrete incidence
realization sends the complete universal chart ideal to zero. -/
theorem IsIncidenceRealization.realChartEvaluation_annihilates_universalChartIdeal
    {V E : Type*} [DecidableEq V] [DecidableEq E]
    {src dst : E → V} {active : Finset E}
    {p : E → Vec3 ℝ} {Y : V → Twist ℝ}
    (hY : SparseNullIncidence.IsIncidenceRealization src dst active p Y)
    (root : V) (chart : active → Fin 3) (selected : Finset active) :
    universalChartIdeal root src dst active chart selected ≤
      RingHom.ker (realChartEvaluation root p Y) := by
  rw [universalChartIdeal, Ideal.span_le]
  intro f hf
  rcases hf with hf | hf
  · obtain ⟨a, rfl⟩ := hf
    change realChartEvaluation root p Y
        (activeCompatibilityGenerator root src dst active chart a) = 0
    exact IsIncidenceRealization.realChartEvaluation_compatibility_eq_zero
      hY root a.1 a.2.1
  · exact
      IsIncidenceRealization.realChartEvaluation_annihilates_selectedNullGeneratorSet
        hY root selected f hf

end

end UniversalHomogeneousChart

end RB31E2E
